sudo: false
dist: trusty
group: deprecated-2017Q4 # To fix NPM timeout errors
language: ruby
rvm:
- 2.4.3
if: branch = master OR repo =~ /-stage/
before_install:
- echo -e "machine github.com\n login $GH_TOKEN" >> ~/.netrc && chmod 600 ~/.netrc
- git submodule add https://github.com/NetAppDocs/jekyll dependencies/jekyll
- gem update --system && gem install bundler && gem update bundler
- if [[ "$TRAVIS_BRANCH" =~ master && $TRAVIS_PULL_REQUEST -eq 0 && -z "$TRAVIS_PULL_REQUEST_BRANCH" ]]; then
  echo "Site Translation Enabled";
  else
  echo "Skipping Translation";
  unset MT_TOKEN;
  fi
- mv dependencies/jekyll/prod-build.sh ./ && ./prod-build.sh
script:
- bundle exec rake deploy
