---
sidebar: sidebar
permalink: concept_aiq_AFF_SE_appendix.html
keywords: Active IQ, storage efficiency, AFF, FAQs, storage efficiency calculator
summary: Provides the definition of the storage efficiency terminology.
---

= Appendix
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/AFFSEcalculator

== Ratio Definitions

*Total Effective Storage Capacity Ratio*

This is the ratio of the total logical space used by the active file system, snapshots, and clones compared to the total amount of physical space on disk that is needed to store those copies. It can be viewed as the total amount of space savings due to all NetApp technologies, including in-line data compaction, in-line deduplication, in-line compression, volume snapshots, volume clones, LUN and file clones, and background deduplication. This value does not include any thin provisioning savings.

*Snapshots and Clones*

This is the ratio of logical data used by volume clones and volume snapshots compared to the number of physical blocks needed to store the data. It does not include space savings due to in- line deduplication or in-line compression. This ratio includes space savings due to newly provisioned LUNs (which reserve space in the FlexVol), even if no data has been written to the LUN yet and the volume is not space-guaranteed.

*Deduplication and Compression*

This is the ratio of space savings due to in-line data compression, in-line deduplication, in-line zero-block elimination and background deduplication. It is the ratio equivalent of the output of df-s. Space savings due to file clones and LUN clones is also included in this ratio. This value does not include any thin provisioning savings.

*In-line Data Compaction*

This is the ratio of logical data used in the aggregate compared to the physical blocks used at the aggregate level to store the data. It represents the space savings due to in-line data compaction.

*Total Logical Used Capacity*

This is the sum of the used capacity represented by all files and LUNs attached to the controller. For example, if you write a total of 10GiB of data to two different files, regardless if compression or deduplication saves space, this value will be 10GiB.

*Total Physical Used Capacity*

This is the sum of the used physical capacity represented by all files and LUNs attached to the controller. For example, if you write a total of 10GiB of data to two different files, and in-line data compaction, deduplication and compression reduce the total amount of physical capacity used to 1 GiB, this value will be 1 GiB. In this case, the Total Effective Storage Capacity ratio for the controller would be 10:1.
