---
sidebar: sidebar
permalink: concept_overview_API_service.html
keywords: API services, access token, refresh token, API Catalog
summary: Provides an overview of the API services feature.
---

= Understand API Services
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Using the Active IQ APIs, you’ll be able to pull data of interest and integrate it directly into your company’s workflow, viewing it when and how you want to see it. This type of automation and integration can add efficiency to your business and allow you to focus on the items of most importance to you. Your use-case may involve automating ticket creation to track needed work items to completion, or it may be to create an internal dashboard of key parameters, or perhaps something entirely unique to the way your business operates.

== API Catalog

Even prior to authorization, you can browse through the available *API Catalog* to see the types of data that are offered through the service. The Catalog contains broad categories such as Capacity, Efficiency, Health, and so on. Inside each category there are individual APIs that can be used to pull a specific set of data from within that broad category. The API Catalog also shows the construction of the query as well as the specifics of what is returned.

== Using the APIs

Once you generate tokens and are authorized, you can leverage tokens to make queries and retrieve data. It is also possible to test out an API from within the API Catalog to see first-hand how the query works and the type of data that is returned. This is a great way to make sure you understand how an API will work prior to building out the code framework in your system.

video::GQskCeCrtQA[youtube, width=848, height=480]
