---
sidebar: sidebar
permalink: concept_get_started_with_health_check_dashboard.html
keywords: activeiq, health check, health, HCA, health check dashboard, autosupport, autosupport adoption, recommended configuration, best practices, support, support and entitlements, support contract, contracts, active contracts, expired contracts, nearing-expiration, key recommendations, recommendations,  digital advisor, features, recommended software
summary: Provides information about the dashboard, health scores, features, and the widgets.
---

= Get started with Health Check Dashboard
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This dashboard provides an at-a-glance summary of your installed base through the following widgets:

* *AutoSupport Adoption*: Displays the number and percentage of systems with AutoSupport enabled. You can also view systems marked as ‘Declined’, those with *HTTPS* and *AutoSupport on Demand* enabled, as well as *Loss of Signal* for those systems that have stopped sending AutoSupport data in the last 7 days.
To view your health check score and information about the systems in your install base, click the *AutoSupport Adoption* widget.
+
* *Recommended Configuration*: Displays systems that are compliant and non-compliant as per the *Recommended Configuration* widget. It helps you take actions to ensure that your systems are well configured across your installed base. You can view the score provided on the dashboard and take actions based on the key recommendations which are provided in order of priority.
* *Recommended Software*: Displays a consolidated list of all the software and firmware upgrades and currency recommendations. You can view the systems with AutoSupport enabled that should be at either the minimum or latest software or firmware versions.
+
* *Support & Entitlements*: Displays support contracts that have expired and those that are nearing expiration within 6 to 12 months. It displays end of support platforms, disks, shelves, entitlement compliance, pending expirations, and end of support for platform and hardware is not applicable.
You can view the health check score provided on the dashboard and take actions based on the key recommendations, which are provided in order of priority.
To view detailed information about support contracts, click the *Support & Entitlements* widget. You can also renew your support contracts using this widget.
+
* *Best Practices*: Displays the health check score by assessing the best practices attributes of your storage system — performance & efficiency, availability & protection, capacity, configuration, and security vulnerabilities. NetApp best practices help sustain system health, which optimizes the performance of your installed base.
+
* *Technical Cases*: Provides you with a detailed view of your technical case history, by case type and open or closed status, over selectable time ranges.  You can drill into case groups as well as view case details through link:https://mysupport.netapp.com//[NetApp Support Site^] or other case portals.
