---
sidebar: sidebar
permalink: concept_working_with_inventory_file.html
keywords: inventory file, file format
summary: Provides information about working with the inventory file.
---

= Update the inventory file for the AFF and FAS firmware update 
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The inventory file consists of the cluster management LIFs of the systems that are eligible for firmware updates. It contains the list of clusters with disk and shelf firmware filename information wherever applicable.

For service processor firmware update, node hostnames and SP/BMC IP is included in the inventory file.

== Inventory file format

The following is a sample inventory file format with both disk and shelf firmware updates:

----
clusters:
  - clustername: <cluster management LIF-1>
    disk_fw_file: all.zip
    shelf_fw_file: all_shelf_fw.zip

  - clustername: <cluster management LIF-2>
    disk_fw_file: all.zip
    sp_nodes:
    - hostname: <node hostname 1>
      sp_fw_file: SP_FW_308-03990_11.5.zip
      sp_fw_type: bmc
      sp_fw_ver: '11.5'
      sp_ip: <BMC IP>
    - hostname: <node hostname 2>
      sp_fw_file: SP_FW_308-03991_5.8.zip
      sp_fw_type: sp
      sp_fw_ver: '5.8'
      sp_ip: <SP IP>
----

In the example, both shelf and disk firmware updates are applicable on cluster-1 and disk and SP/BMC firmware updates are applicable on cluster-2.

== Delete a cluster from the inventory file

In case you do not want to apply firmware updates on a particular cluster, you can remove the cluster from the inventory file.

For example, if you do not want to apply disk firmware updates on cluster-2, you can remove it from the inventory file using the following command:

----
clusters:
  - clustername: <cluster management LIF-1>
    disk_fw_file: all.zip
    shelf_fw_file: all_shelf_fw.zip
----

You can observe that all the data for cluster-2 has been deleted.

If you want to apply only disk firmware updates on cluster-1 and not shelf firmware updates, you can do so using the following command:

----
clusters:
  - clustername: <cluster management LIF-1>
    disk_fw_file: all.zip
----

You can see that the _shelf_fw_file_ key and value have been removed from cluster-1.

NOTE: Manual addition of clusters or controllers is not supported.
