---
sidebar: sidebar
permalink: concept_overview_performance.html
keywords: overview, performance, cluster performance, mode performance, local tier performance
summary: Provides information about the performance of the cluster, node, and local tier.
---

= Understand Performance
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Performance graphs enable you to analyze performance of your storage devices. You can view detailed performance graphs for an ONTAP cluster or multiple nodes of an ONTAP cluster. It displays cluster nodes for systems running ONTAP 8.3.1 and later. These graphs provide historical performance data, which can be used for understanding performance trend and pattern analysis. You can select a date from calendar to view performance graphs for a day, week, month, and two months. You can select multiple nodes to view a particular graph at the same time.

You have an option to set preferences, for example, you can view either one graph for three nodes or two graphs for three nodes.

When the graph is first displayed, 1-week tab is preselected and it presents data for 1 week in a graphical format to make it easier to understand large quantities of data and its relationship between different series of data. If you want to reset the date range, for example, you can click 1-month tab and select dates in the calendar.

You also have an option to zoom in performance graph; the individual data points are displayed.

video::fWrHYX17xT8[youtube, width=848, height=480]
