--
sidebar: sidebar
permalink: concept_ug_api_getting_started_sample_api.html
keywords: Active IQ, user guide, API services. sample API
summary: Provides a sample API in different languages to help you get started.
---

= Getting Started (Sample API)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/UserGuide

APIs can be written in different languages. The languages that are supported are Curl, Java, Android, Obj-C, JavaScript, C#, PHP, Perl, and Python.

Let's look at a sample API. The *getAccessToken* API  is used to generate a new access token using a valid refresh token.

The following is the API in JavaScript:

|=======================================================================================================
|var   ActiveIqPublicApi = require('active_iq_public_api');

var api = new ActiveIqPublicApi.AccessTokenApi()

var tokenManageraccessToken = ; // {TokenManageraccessToken}


var callback = function(error, data, response) {
  if (error) {
    console.error(error);
  } else {
    console.log('API called successfully. Returned data: ' + data);
  }
};
api.getAccessToken(tokenManageraccessToken, callback);
|=======================================================================================================

The following is the API in Python:

|=======================================================================================================
|from __future__ import print_statement
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint

# create an instance of the API class
api_instance = swagger_client.AccessTokenApi()
tokenManageraccessToken =  # TokenManageraccessToken |

try:
    # Generates a new access token using a valid refresh token.
    api_response = api_instance.get_access_token(tokenManageraccessToken)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling AccessTokenApi->getAccessToken: %s\n" % e)
|=======================================================================================================
