---
sidebar: sidebar
permalink: concept_understand_sustainability_dashboard.html
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, bluexp
summary: Provides information to familiarize yourself with the Sustainability Dashboard.
---

= Learn about BlueXP sustainability dashboard
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Sustainability dashboard enables you to reduce the energy consumption and helps you to work towards your environmental goals. This enables you to align your storage systems with eco-friendly practices, and achieve the sustainability targets. 

== What can you do with BlueXP sustainability dashboard

You can view the sustainability score, and projected usage of power, direct carbon, and heat. You can adjust the carbon mitigation percentage for specific sites. Based on the sustainability score, you can assess your overall sustainability posture and implement NetApp's recommended actions to improve the score. 

You can also view the sustainability score at the cluster level. The data provided at the cluster level can also help to identify clusters that can be moved to more efficient storage, achieving the right balance between performance and power efficiency.

To get the best results from the dashboard, you must enable AutoSupport. If AutoSupport is not enabled, the data will be based on product specifications. To get real-time power details, you need to enable Cloud Insights.

== Supported environments
NetApp ONTAP systems including AFF, both A-series and C-series, FAS, and Cloud Volumes ONTAP (CVO) are supported.

== Benefits of using BlueXP sustainability dashboard
The sustainability dashboard provides AI-driven actionable recommendations and guided solutions to improve your sustainability posture, enabling you to:

* Lower storage costs
* Reduce carbon footprint
* Improve energy efficiency 

== Cost
NetApp does not charge you for using the BlueXP sustainability dashboard. You can utilize it with your active support contract.

== Licensing
No special license is required to access this dashboard. You can utilize it with your active support contract if you have enabled AutoSupport for your systems.








