---
sidebar: sidebar
permalink: concept_understand_activeiq_features.html
keywords: digital advisor, features, upgrade, support offering
summary: Provides information about the dashboard, watchlists, features, and the widgets.
---

= Learn about Digital Advisor features
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can view the overall status of your storage system, high-level information about the wellness of the system, inventory, planning, upgrades, and valuable insights at a watchlist level using Digital Advisor.

When you access Digital Advisor for the first time, you can either create a watchlist or search for a customer name, site name, group name, StorageGRID, hostname, cluster, serial number, or system ID.

You should also be aware of the colors applied to the cards, which indicate the severity and type of risks.

The following are some of the features of Digital Advisor:

* View multiple watchlists, actionable and useful at-a-glance views of information.
* Gain insights regarding all the risks to your storage system and the actions to mitigate the risks.
* Mitigate risks using Active IQ Unified Manager.
* Upgrade your storage system.
* View the sustainability score, and projected usage of power, direct carbon, and heat. Based on the sustainability score, assess the overall efficiency of your storage systems and align with the NetApp's recommended actions to improve the score. link:learn-about-sustainability.html[Learn more^].
* View data reduction ratio, the logical space used, the physical space used, and the total data saved for storage systems running ONTAP 9.1 and later.
* Analyze the performance of your storage devices by viewing the graphical format of performance data.
* Get information about the hardware and software that have expired or are near-expiration within the next 6 months.
* Update your ONTAP firmware using Ansible.
* Get details about systems that have exceeded 90% capacity or are nearing 90% capacity.
* View detailed physical and logical configuration information, including a summary of the cluster and node configuration, the local tier and volume information, the network interface and port information, a stack diagram detailing information about the disks and shelves, and a few cable visualizations.
* Provide cross-stack information and insights that are beneficial for troubleshooting, upgrade assessments, solution validation, and migration.
* Check the compatibility of hosts, and provide upgrade recommendations for host operating systems, drivers, and .
* Arrive at exactly what you want to find in a smarter and faster manner.

NOTE: You can upgrade the support offering from the *Configuration* widget on the system dashboard to gain insights on your install base and receive personalized support.
