---
sidebar: sidebar
permalink: concept_aiq_value_report.html
keywords: Active IQ, value report
summary: Provides an overview of the value report feature.
---

= Value Report
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/UserGuide

The value report is a summary of benefits you received through Active IQ and your Support Contract.
For selected systems, the value report consolidates the following benefits from last one year.

[cols=",",options="header",]
|========================================================================================================================================
|Components of value report |What does value report show and why should you care?
|Support cases opened and resolved |This component summarizes all support cases that were resolved during the last year, for selected systems. NetApp invests significantly in enhancing its product telemetry and support automation capabilities. As a result, you see improvements in resolution time for cases as NetApp narrows down issues faster and ensures support cases are handled most efficiently by NetApp Support personnel.

This summary also includes cases you may have logged through the NetApp Support Site or by calling NetApp Support.

One of the biggest benefits you receive from your support contract is the resolution of support cases logged for your systems.
|Software upgrades |Value report summarizes all ONTAP upgrades you have performed for selected systems over the last one year.

Software upgrades help improve system reliability and it turn better serves your business applications. Additionally, software upgrades also allow you take advantage of newer features and functionalities.

If you have a valid Support contract, you continue to receive newer and better software for your systems.
|Unique applications detected using signatures and heuristics |Value report shows applications detected for selected systems using signatures, heuristics, and other advanced algorithms applied by NetApp to your system telemetry.

This information is valuable for determining which applications are being served using systems included in the Value Report and helps you make more informed decisions while you are deciding whether to renew support contracts.

If NetApp systems are serving your business applications, you should always consider renewing support contract to ensure you receive ongoing and timely support for your systems.
|Storage efficiency savings |For ONTAP 9.1 and above systems, this component of the value report demonstrates how much savings you have received by taking advantage of various NetApp storage efficiency features including deduplication, compression, Snapshot copies, clones, and compaction.

When you renew the support contract, you will be able to leverage the latest software from ONTAP to get more savings from improvement to existing efficiency features and new efficiency features that NetApp may introduce.
|Days till earliest contract |This information in the value report allows you to prepare better for support contract renewal.

If you have few days till the earliest contract renewal, you should contact Support Contract Renewal team through the support renewal capability in your Active IQ dashboard or reach out to your contact for NetApp systems.
|Proactive System Risks |NetApp makes significant ongoing investments to detect risks in your installed base proactively. After detecting these risks, we classify risks by impact and notify you how to mitigate these risks. To further help with mitigation, in Active IQ, we also show whether the mitigation is non-disruptive (for example, a simple configuration change) or disruptive (for example, a major upgrade) so that you can better plan your mitigation.

In this section of the Value Report, for selected systems, you will see a summary of the following:
* Total risks signatures checked for selected systems
* System risks mitigated – each of these mitigated risks equate to a problem that you avoided.

Proactive risk notifications fall in following categories:

* Configuration
* Security
* Performance and Efficiency
* Capacity
* Availability and protection
|========================================================================================================================================
