---
sidebar: sidebar
permalink: concept_learn_sustainability.html
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, bluexp, benefits, ONTAP
summary: Provides information to familiarize yourself with the BlueXP sustainability.
---

= Learn about BlueXP sustainability
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Sustainability, as a service, allows you to reduce the energy consumption and enables you to work towards your environmental goals. This enables you to align your storage systems with eco-friendly practices and achieve the sustainability targets.

You can use the BlueXP sustainability dashboard to meet your environmental goals. You can view the sustainability score, and projected usage of power, direct carbon, and heat in the sustainability dashboard. You can adjust the carbon mitigation percentage for specific sites.You can also view the sustainability score at the cluster level. Based on the sustainability score, you can assess your overall sustainability posture and implement NetApp’s recommended actions to improve the score.link:task_access_sustainability_dashboard.html[Learn more].

== Benefits of BlueXP sustainability 

BlueXP sustainability offers the following benefits:

* Accelerate performance by reducing the number of storage devices to store the same amount of data.
* Lower storage costs by optimizing storage systems utilization. 
* Reduce carbon footprints by using renewable energy at data centers.
* Improve energy efficiency by implementing energy-efficient policies.

== Supported environments
NetApp ONTAP systems including AFF, both A-series and C-series, FAS, and Cloud Volumes ONTAP (CVO) are supported.

== Cost
NetApp does not charge you for using BlueXP sustainability. You can utilize it with your active support contract.

== Licensing
No special license is required to access BlueXP sustainability. You can utilize it with your active support contract if you have enabled AutoSupport for your systems.










