---
sidebar: sidebar
permalink: concept_ug_hci_expansion_advisor.html
keywords: Active IQ, user guide, HCI expansion advisor
summary: Provides an overview of the HCI expansion advisor feature.
---

= HCI Expansion Advisor
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/UserGuide

HCI Expansion Advisor enables you to assess your NetApp HCI systems to determine whether you need to add compute and storage nodes for new and growing workloads.

Expansion Advisor shows the details about the current configuration of your cluster, as well as performance details for compute and storage over the last 30 days. You can specify the growth percentage for an existing workload, or you can enter details about a new workload that you want to add to the system. Expansion Advisor uses this information to recommend whether you need additional compute and storage nodes to accommodate the workload.

When you’re ready to add compute or storage nodes, you can click *Request Expansion* to send a request for the additional compute and storage nodes. After receiving request, NetApp/Partner contacts you for additional information.

=== Aggregated View of Multiple Customers (Partners Only)

Available from the *My Systems* link on the top banner of the application, this aggregated view provides partners (only) with a way to see all of their customers’ information from a single screen. The view displays a list of partners’ customers, provides a count of the systems for each customer, and shows which sites these customers have.

In addition to these details, this view also shows the number of risks and end-of-support components for each customer and site, as well as AutoSupport adoption for each customer.

This view also offers a detailed worksheet that you can download for each customer. The downloaded report includes the following fields:

[cols=",",]
|=======================
a|
* Cluster Name
* Hostname
* Serial #
* System ID
* Customer
* Site
* Group
* Entitled Access Status
* Last AutoSupport Date

a|
* # of Risks
* # of EOS HW
* Model
* Data ONTAP Version
* Ship Date
* Contract End Date
* Contact Information
* Name, E-Mail, Phone
