---
sidebar: sidebar
permalink: digital-advisor-integration-with-bluexp.html
keywords: digital advisor, integration, bluexp
summary: "Digital Advisor is now fully integrated with NetApp Console. You can now manage your clusters and access all the features of Digital Advisor from the NetApp Console user interface (UI)."
---

= Digital Advisor integration with NetApp Console
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Digital Advisor is now fully integrated with NetApp Console. You can now manage your clusters and access all the features of Digital Advisor from the Console user interface (UI).

Using the Console, IT experts and cloud architects can centrally manage their hybrid multi-cloud infrastructure. All you need is a NetApp Support Site (NSS) account to access Digital Advisor in the Console.

== NetApp Console

Digital Advisor is accessible through the NetApp Console.

The NetApp Console provides centralized management of NetApp storage and data services across on-premises and cloud environments at enterprise scale. The Console is required to access and use NetApp data services. As a management interface, it enables you to manage many storage resources from one interface. Console administrators can control access to storage and services for all systems within the enterprise.

You don’t need a license or subscription to start using NetApp Console and you only incur charges when you need to deploy Console agents in your cloud to ensure connectivity to your storage systems or NetApp data services. However, some NetApp data services accessible from the Console are licensed or subscription-based.

Learn more about the https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html[NetApp Console].

== Access Digital Advisor in NetApp Console

You can access Digital Advisor from the Console to manage your cluster.

.Steps
. Open a web browser and go to https://cloudmanager.netapp.com/app-redirect/active-iq[Console^].

. Select *Log in with your NetApp Support Site Credentials* and enter your credentials.
+
If you have previously created a Console login using an email and password, then you’ll need to continue using that login option instead.

. When prompted, log in with your NetApp Support Site credentials.
+
This login is different from the login completed in step 2. In step 2, you logged in to the Console. Now you’re logging in to Digital Advisor.

*Result*

All your existing watchlists and configurations show up and you can now use Digital Advisor like you typically do.


