---
sidebar: sidebar
permalink: digital-advisor-integration-with-bluexp.html
keywords: digital advisor, integration, bluexp
summary: Digital Advisor is available in BlueXP, our unified platform for hybrid multicloud environments.
---

= Digital Advisor integration with BlueXP
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Digital Advisor (formerly Active IQ Digital Advisor) is now fully integrated with BlueXP (formerly Cloud Manager). Integrating with BlueXP provides a unified management experience that enables you to manage your storage and data assets from a single interface.

== Integration overview

Starting in November 2022, a select set of Digital Advisor users will be encouraged to use Digital Advisor from BlueXP. In the months that follow, Digital Advisor users will be redirected to the Digital Advisor that's available from BlueXP. Groups of users will be redirected to BlueXP each month, until the standalone Digital Advisor is retired.

Not all Digital Advisor users will be migrated at the same time. Users will be migrated periodically over the coming months. When this happens, you'll see a notification in Digital Advisor that you're being redirected to BlueXP.

From BlueXP, you'll have access to the same Digital Advisor interface that you're used to, plus more. BlueXP enables you to create and administer cloud storage (for example, Cloud Volumes ONTAP), use NetApp's data services (for example, Cloud Backup), and control many on-prem and edge storage devices. 

== What to do when you're redirected

<step-by-step details about what happens when you’re redirected, which we'll get from the BlueXP/Digital Advisor teams>

== FAQs

Here are answers to questions that you might have about Digital Advisor integration with BlueXP.

=== What is happening?
Active IQ is being renamed to Digital Advisor and is being integrated into BlueXP, NetApp’s unified management console for hybrid multicloud environments. 

=== Do I have to move to BlueXP immediately?
No. You can continue to use the stand-alone version of Digital Advisor, or you can move to accessing Digital Advisor from BlueXP and enjoy the benefits of the integration. A notification will appear in Digital Advisor when your account has been migrated to BlueXP.

=== Is the Digital Advisor available in BlueXP the same version that I'm used to?
Yes, the Digital Advisor available in BlueXP will be of the same version.

=== Where can I learn more about BlueXP?
Go to the BlueXP documentation to learn more (link will be added).

