---
sidebar: sidebar
permalink: digital-advisor-integration-with-bluexp.html
keywords: digital advisor, integration, bluexp
summary: Digital Advisor is available in BlueXP, our unified platform for hybrid multicloud environments.
---

= Digital Advisor integration with BlueXP (Private Preview)
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Digital Advisor (formerly Active IQ Digital Advisor) is now fully integrated with BlueXP (formerly Cloud Manager). As a private preview, you can now manage your clusters and access all the features of Digital Advisor from the BlueXP user interface (UI). 

Using BlueXP, IT experts and cloud architects can centrally manage their hybrid multi-cloud infrastructure. All you need is a NetApp Support Site (NSS) account to access Digital Advisor in BlueXP.

== Integration overview

Starting in November 2022, as a private preview, Digital Advisor users will be encouraged to use Digital Advisor in BlueXP. From BlueXP, you'll have access to the same Digital Advisor interface that you're used to, plus more. BlueXP enables you to create and administer cloud storage (for example, Cloud Volumes ONTAP), use NetApp's data services (for example, Cloud Backup), and control many on-prem and edge storage devices. 

== Access Digital Advisor in BlueXP

You don’t have to wait until you’re automatically redirected to Digital Advisor in BlueXP. You can start accessing it now.

.Steps
. Open a web browser and go to link:https://cloudmanager.netapp.com.[BlueXP].
. Select *Log in with your NetApp account* and enter your NetApp Support Site credentials.
+
If you previously created a BlueXP login using an email and password, then you’ll need to continue using that login option instead.
. From the left navigation menu, select *Health > Digital Advisor*.
. When prompted, log in with your NetApp Support Site credentials.
+
This login is different from the login completed in step 2. In step 2, you logged in to the BlueXP platform. Now you’re logging in to Digital Advisor. 

*Result*

All your existing watchlists and configurations will show up and you can now use Digital Advisor like you typically do.

== Learn more about BlueXP

link:https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html[Go to the BlueXP documentation to learn more]

== FAQ

Here are answers to questions that you might have about Digital Advisor integration with BlueXP.

=== What is happening?
Active IQ is being renamed to Digital Advisor and is being integrated into BlueXP, NetApp’s unified management console for hybrid multicloud environments. 

=== Do I have to move to BlueXP immediately?
No. You can continue to use the standalone version of Digital Advisor for now. 

=== Is the Digital Advisor available in BlueXP the same version that I'm used to?
Yes, the Digital Advisor available in BlueXP is the same as the standalone version.

