---
sidebar: sidebar
permalink: digital-advisor-integration-with-bluexp.html
keywords: digital advisor, integration, bluexp
summary: Digital Advisor is available in BlueXP, our unified platform for hybrid multicloud environments.
---

= Digital Advisor integration with BlueXP
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Digital Advisor (formerly Active IQ Digital Advisor) is now fully integrated with BlueXP (formerly Cloud Manager). Integrating with BlueXP provides a unified management experience that enables you to manage your storage and data assets from a single interface.

== Integration overview

Starting in November 2022, a select set of Digital Advisor users will be encouraged to use Digital Advisor from BlueXP. In the months that follow, Digital Advisor users will be redirected to the Digital Advisor that's available from BlueXP. Groups of users will be redirected to BlueXP each month, until the standalone Digital Advisor is retired.

Not all Digital Advisor users will be migrated at the same time. Users will be migrated periodically over the coming months. When this happens, you'll see a notification in Digital Advisor that you're being redirected to BlueXP.

From BlueXP, you'll have access to the same Digital Advisor interface that you're used to, plus more. BlueXP enables you to create and administer cloud storage (for example, Cloud Volumes ONTAP), use NetApp's data services (for example, Cloud Backup), and control many on-prem and edge storage devices. 

== What to do when you're redirected

<step-by-step details about what happens when you’re redirected, which we'll get from the BlueXP/Digital Advisor teams>

== Access Digital Advisor in BlueXP

You don’t have to wait until you’re automatically redirected to Digital Advisor in BlueXP. You can start accessing it now.

.Steps
. Open a web browser and go to link:https://cloudmanager.netapp.com[BlueXP].
. Select *Log in with your NetApp account* and enter your NetApp Support Site credentials.
+
If you previously created a BlueXP login using an email and password, then you’ll need to continue using that login option instead.
From the left navigation menu, select *Health > Digital Advisor*.
When prompted, log in with your NetApp Support Site credentials.
+
This login is different from the login completed in step 2. In step 2, you logged in to the BlueXP platform. Now you’re logging in to Digital Advisor. 

*Result*

You can now use Digital Advisor like you typically do.

== Learn more about BlueXP

Go to the BlueXP documentation to learn more (link will be added soon).

== FAQ

Here are answers to questions that you might have about Digital Advisor integration with BlueXP.

=== What is happening?
Active IQ is being renamed to Digital Advisor and is being integrated into BlueXP, NetApp’s unified management console for hybrid multicloud environments. 

=== Do I have to move to BlueXP immediately?
No. You can continue to use the standalone version of Digital Advisor for now. A notification will appear in Digital Advisor when your account has been migrated to BlueXP.

=== Is the Digital Advisor available in BlueXP the same version that I'm used to?
Yes, the Digital Advisor available in BlueXPis the same as the standalone version.

