---
sidebar: sidebar
permalink: index.html
summary: Active IQ Digital Advisor Documentation.
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

Active IQ enables you to optimize your data infrastructure across your global hybrid cloud by delivering actionable predictive analytics and proactive support through a cloud-based portal and mobile app.

Active IQ's cloud-based services leverage community wisdom and peer comparisons that are drawn from NetApp's massive installed base, combining these insights with AutoSupport telemetry and My AutoSupport features to deliver an advanced set of unparalleled analytics services.

The new version of Active IQ, known as Active IQ Digital Advisor, is simple and enables you to quickly identify and take the next best action to improve the wellness of your NetApp environment. Active IQ Digital Advisor has been enhanced and redesigned to help you perform tasks more effectively.
We are incrementally enhancing this version and urge you to try out this new experience and give us your feedback at ng-activeiq-feedback@netapp.com.

=== Accessing Active IQ Web Portal and Downloading the Mobile App

* link:https://mysupport.netapp.com/myautosupport/home.html[Active IQ Web Portal]
* link:https://itunes.apple.com/us/app/my-autosupport/id1230542480?ls=1&mt=8[Active IQ Mobile App Download (iOS)]
* link:https://play.google.com/store/apps/details?id=com.netapp.myautosupport[Active IQ Mobile App Download (Android)]

NOTE: You must have valid NetApp Support site credentials to log in. If you do not have an account and are just getting started with NetApp Support, please visit - https://mysupport.netapp.com/info/web/ECMP1150550.html

Active IQ displays systems with a valid support contract. If contracts expire, there is a grace period of 90 days during which the systems continue to be visible. Thereafter, the systems are not searchable or visible within Active IQ.

=== Documentation and Support

* link:https://www.netapp.com/us/documentation/active-iq.aspx[Documentation Resources]
* link:https://mysupport.netapp.com/myautosupport/dist/index.html#/feedback[Report Issues]
* link:http://communities.netapp.com/community/products_and_solutions/efficient_it/my_autosupport_and_autosupport?view=overview[User Community]
* link:https://twitter.com/NetAppActiveIQ[Follow us on Twitter]
