---
sidebar: sidebar
permalink: index.html
summary: Active IQ Digital Advisor Documentation.
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

Active IQ enables you to optimize your data infrastructure across your global hybrid cloud by delivering actionable predictive analytics and proactive support through a cloud-based portal and mobile app.

Active IQ's cloud-based services leverage community wisdom and peer comparisons that are drawn from NetApp's massive installed base, combining these insights with AutoSupport telemetry and My AutoSupport features to deliver an advanced set of unparalleled analytics services.

=== Accessing Active IQ Web Portal and Downloading the Mobile App

[cols=",",options="header",]
|=======================================================================================================
|Active IQ Web Portal |https://mysupport.netapp.com/myautosupport/home.html[https://activeiq.netapp.com]
|Active IQ Mobile App Download (iOS) |https://itunes.apple.com/us/app/my-autosupport/id1230542480?ls=1&mt=8
|Active IQ Mobile App Download (Android) |https://play.google.com/store/apps/details?id=com.netapp.myautosupport
|=======================================================================================================

NOTE: You must have valid NetApp Support site credentials to log in. If you do not have an account and are just getting started with NetApp Support, please visit - https://mysupport.netapp.com/info/web/ECMP1150550.html

Active IQ displays systems with a valid support contract. If contracts expire, there is a grace period of 90 days during which the systems continue to be visible. Thereafter, the systems are not searchable or visible within Active IQ.

=== Documentation, Feedback, and Support

[cols=",",options="header",]
|========================================================================================================================================
|Documentation Resources |https://www.netapp.com/us/documentation/active-iq.aspx
|Report Issues |https://mysupport.netapp.com/myautosupport/dist/index.html#/feedback
|Feedback & Enhancement Requests |ng-activeiq-feedback@netapp.com
|User Community |http://communities.netapp.com/community/products_and_solutions/efficient_it/my_autosupport_and_autosupport?view=overview
|Follow us on Twitter |https://twitter.com/NetAppActiveIQ
|========================================================================================================================================
