---
sidebar: sidebar
permalink: learn_BlueXP_sustainability.html
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, bluexp, benefits, ONTAP
summary: Provides information about sustainability that allows you to reduce the energy consumption and enables you to work towards your environmental goals.
---

= Learn about sustainability
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Sustainability, as a service, allows you to reduce the energy consumption and enables you to work towards your environmental goals. This enables you to align your storage systems with eco-friendly practices and achieve the sustainability targets.

You can use the Sustainability dashboard to view the sustainability score, and projected usage of power, direct carbon, and heat from the sustainability dashboard. You can adjust the carbon mitigation percentage for specific sites. You can also view the sustainability score at the cluster level. Based on the sustainability score, you can assess the sustainability posture and implement NetApp’s recommended actions to improve the score. To learn more about the Sustainability dashboard, go to link:BlueXP_sustainability_dashboard_overview.html[Sustainability dashboard overview].

NOTE: ##Sustainability is supported on Cloud Volumes ONTAP, AFF systems (A-Series and C-Series), E-Series, FAS, and StorageGRID systems.##

You can view the following video to understand the Sustainability dashboard:

video::yNRHeOvbGX8[youtube, width=848, height=480]

== Benefits of sustainability 

Sustainability offers the following benefits:

* Accelerate performance by reducing the number of storage devices to store the same amount of data.
* Lower storage costs by optimizing storage systems utilization. 
* Reduce carbon footprints by using renewable energy at data centers.
* Improve energy efficiency by implementing energy-efficient policies.













