---
settings:
  name: Digital Advisor
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
   
sidebar:
  entries:
    - title: Digital Advisor docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new in Digital Advisor
          url: /reference_new_activeiq.html
        - title: Known limitations in Digital Advisor
          url: /reference_limitations_activeiq.html
    - title: Get started
      entries:
        - title: Quick start for Digital Advisor
          url: /concept_getting_started_2.html
        - title: Learn about Digital Advisor features
          url: /concept_understand_activeiq_features.html
        - title: Access Digital Advisor in NetApp Console
          url: /digital-advisor-integration-with-console.html
        - title: Learn about Digital Advisor
          url: /concept_key_terms.html
        - title: Learn about AutoSupport in Digital Advisor
          url: /concept_autosupport.html
        - title: Log in to Digital Advisor
          url: /task_login_activeiq.html
        - title: Provision watchlist
          entries:
            - title: Learn about watchlists in Digital Advisor
              url: /concept_overview_dashboard.html
            - title: Create a watchlist in Digital Advisor
              url: /task_add_watchlist.html
            - title: Manage a watchlist in Digital Advisor
              url: /task_manage_watchlists.html
        - title: FAQ for Digital Advisor
          url: reference_aiq_faq.html
    - title: Use Digital Advisor
      entries:
        - title: Analyze wellness attributes
          entries:
            - title: Learn about wellness widget in Digital Advisor
              url: /concept_overview_wellness.html
            - title: View storage system risks in Digital Advisor and take corrective actions
              url: /task_view_risk_and_take_action.html
            - title: Detect security risks with Digital Advisor and take corrective actions
              url: /task_increase_protection_against_hackers_and_Ransomware_attacks.html
            - title: Protect storage systems managed by Digital Advisor from ransomware risks
              url: /task_protect_systems_against_ransomware_risks.html
            - title: Analyze wellness attributes in Digital Advisor and acknowledge risks
              url: /task_view_and_acknowledge_risks.html
            - title: View your storage system risk history in Digital Advisor
              url: /task_view_wellness_history.html
            - title: View risks in Digital Advisor and mitigate risks using Unified Manager or Ansible Playbook
              url: /task_view_risks_remediated_unified_manager.html
            - title: Use Digital Advisor to fix critical risks identified in the  Availability and Protection widget
              url: /task_avoid_the_downtime_and_possible_data_loss.html
            - title: Subscribe to storage system health notifications from Digital Advisor
              url: /task_subscribe_to_wellness_review_email.html
            - title: Identify software and hardware renewals for your storage system from Digital Advisor
              url: /task_renew_software_and_hardware.html
            - title: View the health of clusters and nodes using ClusterViewer widget in Digitial Advisor
              url: /task_analyze_wellness_clusters_and_nodes.html
        - title: Analyze the sustainability of your storage system
          entries:
            - title: Learn about sustainability with Digital Advisor
              url: /learn-about-sustainability.html
            - title: Access the Sustainability dashboard in Digital Advisor
              url: /get_started_sustainability_dashboard.html
            - title: Learn about Sustainability dashboard features in Digital Advisor
              url: /sustainability-dashboard-overview.html
            - title: Improve your storage system sustainability score from Digital Advisor
              url: /improve_sustainability_score.html
        - title: Generate an upgrade plan
          entries:
            - title: Learn about generating an ONTAP upgrade plan in Digital Advisor
              url: /upgrade_advisor_overview.html
            - title: Generate an ONTAP upgrade plan for single and multiple clusters in Digital Advisor
              url: /generate_upgrade_plan_single_multiple_clusters.html      
            - title: View firmware update recommendations in Digital Advisor
              url: /view-firmware-update-recommendations.html            
        - title: View system details
          entries:
            - title: View your storage system inventory details in Digital Advisor
              url: /task_view_inventory_details.html
            - title: Use Digital Advisor to view virtual machines data available in Data Infrastructure Insights
              url: /task-integrating-with-cloud-insights-to-view-vm-details.html
            - title: View support cases and storage system details with the Valuable Insights widget in Digital Advisor
              url: /task_view_valuable_insight_widget.html
            - title: View capacity utilization with NetApp Keystone subscription in Digital Advisor
              url: /view_keystone_capacity_utilization.html
        - title: Identify system requirements proactively
          entries:
            - title: Manage your storage system capacity requirements with Planning widget in Digital Advisor 
              url: /concept_overview_planning.html
            - title: Identify storage systems nearing capacity limits in Digital Advisor
              url: /task_identify_capacity_system.html
            - title: Manage volume storage capacity thresholds in Digital Advisor
              url: /task_avoid_a_volume_filling_up_to_prevent_an_outage.html  
            - title: Determine if a technology refresh is recommended for your storage system in  Digital Advisor
              url: /evaluate-tech-refresh.html
            - title: Renew software and hardware of your storage system
              url: /task_renew_software_and_hardware.html
        - title: Analyze your storage system health with cloud recommendations in Digital Advisor
          url: /task-informed-decisions-based-on-cloud-recommendations.html
        - title: Identify configuration deviation
          entries:
            - title: Detect configuration deviations for your storage system with Digital Advisor 
              url: /concept_overview_config_drift.html
            - title: Add a config drift template for your storage system in Digital Advisor
              url: /task_add_config_drift_template.html
            - title: Compare config drift templates in Digital Advisor
              url: /task_compare_config_drift_template.html
            - title: Generate a config drift timeline report in Digital Advisor
              url: /task_generate_drift_timeline_report.html
            - title: Manage config drift templates in Digital Advisor
              url: /task_manage_template.html
        - title: Improve the efficiency and performance of your storage system
          entries:
            - title: View capacity and storage efficiency savings in Digital Advisor
              url: /task_analyze_storage_efficiency.html
            - title: View storage system performance graphs in Digital Advisor
              url: /task_view_performance_graphs.html
        - title: Analyze the health of your storage system
          entries:
            - title: Learn about Health Check dashboard in Digital Advisor
              url: /concept_understand_health_check_dashboard.html
            - title: Get started with Health Check dashboard
              url: /concept_get_started_with_health_check_dashboard.html
            - title: Renew your support contracts in Digital Advisor
              url: /task_renew_support_contracts_for_your_systems.html
        - title: Upgrade to optimize your install base
          entries:
            - title: Upgrade your support offering in Digital Advisor
              url: /task_upgrade_support_offering.html
            - title: Update your AFF and FAS firmware using Ansible Playbook
              entries:
                - title: Download the AFF and FAS firmware Ansible package from Digital Advisor
                  url: /task_update_AFF_FAS_firmware.html
                - title: Update AFF and FAS firmware using an Ansible package (experienced users) 
                  url: /task_install_execute_firmware_update_exp_user.html
                - title: Install and execute AFF and FAS firmware Ansible automation package (beginners)
                  entries:
                    - title: Host AFF and FAS firmware files on a web server 
                      url: /task_hosting_firmware_files_using_web_server.html
                    - title: Update the inventory file for the AFF and FAS firmware update 
                      url: /concept_working_with_inventory_file.html
                    - title: Run the Ansible playbook using the NetApp Docker image
                      url: /task_execute_ansible_playbook_using_docker.html
                    - title: Run the Ansible playbook without the NetApp Docker image
                      url: /task_execute_ansible_playbook_without_docker.html
                    - title: Validate the AFF and FAS firmware installation on your storage system
                      url: /task_validate_firmware_installation.html
        - title: Integrate data using APIs
          entries:
            - title: Learn about Digital Advisor API services
              url: /concept_overview_API_service.html
            - title: Generate tokens to use Digital Advisor API services
              url: /task_generate_tokens_API_services.html
            - title: Use the Digital Advisor API catalog to execute the APIs
              url: /task_view_API_catalog.html
        - title: Generate custom reports
          entries:
            - title: Learn about Digital Advisor reports
              url: /concept_report_types.html
            - title: Generate or schedule a report in Digital Advisor
              url: /task_generate_reports.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /reference_ansible_troubleshoot_feedback_support.html
        - title: Get help
          url: /concept_get_more_information.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: NetApp Console
  repo: console-family
