---
sidebar: sidebar
permalink: reference_aiq_srd_health_summary.html
keywords: system risk, health summary
summary: Provides information about the health summary.
---

= Active IQ health summary
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/systemriskdetails

=== What is the purpose of the health summary section?

Health Summary section proactively identifies risks in deployed NetApp® storage configurations that can negatively affect system performance, availability, and resiliency. Each risk entry contains information about the specific risk to the system, potential negative effects, and links to risk mitigation plans. By addressing identified risks proactively, you can significantly reduce the possibility of unplanned downtime for your NetApp storage system.

=== What is the access policy for this health summary module?

Like all of Active IQ, this module is accessible to all customers whose systems are covered by a valid hardware warranty contract, with AutoSupports enabled.

=== Is there a requirement to correct risks that are identified?

NetApp highly recommends resolving identified risks within suggested time frames to avoid adverse system impacts. A severity suggesting the recommended time frame in which the resolution should be implemented is included in details of each risk: for example, immediately, next scheduled maintenance, and so on. Not resolving identified risks increases your chance of encountering system issues that would have been avoidable if corrective mitigation was undertaken.

=== Is a support case automatically opened for identified risks?

No, cases are not automatically opened for risks.

=== What are the system hardware and software requirements?

The following software and hardware requirements are needed for system risk analysis:

* AutoSupport enabled
* ONTAP and E-Series based systems

=== Are all risks to the system identified?

For functionality that is targeted for risk identification there are exceptions as follows:

* Risks that cannot be identified by analysis of AutoSupport logs are not included. For example, client application configuration parameters not controlled by ONTAP.
* Risks that do not currently have a risk “signature,” a code for detecting the risk in the AutoSupport, are not included. NetApp is continually adding new risk signatures to expand coverage of identified risks.
