---
sidebar: sidebar
permalink: reference_new_activeiq.html
keywords: what's new, features, new
summary: Provides information about the new features in the release.
---

= What's new in Active IQ Digital Advisor
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Active IQ typically introduces a new release every month to bring you the new features and enhancements.

== 14 October 2020
This update includes the following new features, enhancements, and changes:

=== Config Drift
This feature enables you compare the system and cluster configurations and the detect configuration deviations in near real time.

=== Periodic Digest
You can now subscribe to the periodic digest that gives you an overview of your storage system and actions.

=== AutoSupport Alerts
You can now view AutoSupport data and review the details.

=== Email subscription for receiving system status
You can subscribe to receiving monthly email notifications that summarize wellness status of systems—that are nearing their renewal dates and require an upgrade for the NetApp products in your installed base.

=== Reports
You can use the reports feature to generate reports immediately or schedule a report to be generated on a weekly or monthly basis.

== 30 September 2020
This update includes the following new features, enhancements, and changes:

=== AFF and FAS firmware using Ansible Playbook
The documentation has been enhanced to include information about downloading, installing, and executing the AFF and FAS firmware ansible automation package.

== 18 August 2020
This update includes the following new features, enhancements, and changes:

=== Performance
Performance graphs have been enhanced to enable you to assess the performance of the volume. You can navigate and toggle between the node tab, cluster tab, the local tier tab, and the volume tab on the same screen.

=== AFF and FAS firmware using Ansible Playbook
The AFF and FAS firmware screen has been enhanced to provide a better user experience.

== 17 July 2020
This update includes the following new features, enhancements, and changes:

=== Performance
Performance graphs have been enhanced to enable you to assess the performance of the local tier. You can navigate and toggle between the node tab, cluster tab, and the local tier tab on the same screen.

=== Wellness
The wellness attributes have been enhanced to view all the affected systems without having to drill-down to the actions and risks.

== 19 June 2020
This update includes the following new features, enhancements, and changes:

=== Generate report for inventory
You can now generate report of the selected watchlist and emails the report to a maximum of 5 recipients.

=== Performance
Performance graphs have been enhanced to enable you to assess the cluster performance of your storage system. You can navigate and toggle between the node tab and the cluster tab on the same screen.

=== Storage efficiency
The storage efficiency widget has been enhanced to enable you to view the storage efficiency ratio and savings at a cluster level. You can navigate and toggle between the node tab and the cluster tab on the same screen.

=== Update the default home page
You can now provide your feedback and let us know the reason you are the updating the default home page screen for Active IQ.

=== Update to the inventory widget
The inventory widget has been enhanced to improve the user experience, by providing user-friendly date formats, additional columns for end of platform support and end of version support.

== 19 May 2020
This update includes the following new features, enhancements, and changes:

=== Set the default home page
You can now set the default home page screen for Active IQ. You can either set it to Active IQ Digital Advisor or Active IQ Classic.

=== Storage efficiency
You can view the storage efficiency ratio and savings of your storage system with and without Snapshot backups for AFF systems, non-AFF systems, or both. You can view the storage efficiency information at a node level.

=== Performance
Performance graphs enable you to assess the performance of your storage devices in different significant areas.

=== AFF and FAS firmware upgrades using Ansible Playbook
Update the AFF and FAS firmware using Ansible on your storage system to mitigate the identified risks and to keep your storage system up to date.

=== Disabling the wellness score feature
The wellness score feature is being temporarily disabled to improve the scoring algorithm and simplify the overall experience.

== 02 April 2020
This update includes the following new features and enhancements:

=== Onboarding overview video
The onboarding video helps users to quickly get familiar with the options and features of Active IQ Digital Advisor.

=== Wellness score
Wellness score provides customers with a consolidated score of their installed base based on the number of high risks and the expired contracts. Score can be good, average, or poor.

=== Risk summary
The risk summary provides detailed information about the risk, the impact of the risk, the corrective actions.

=== Support for acknowledging and disregarding risks
Provides the option to acknowledge a risk if you do want to mitigate or are unable to mitigate the risk.

== 19 March 2020
This update includes the following new features and enhancements:

=== Upgrade workflow
You can use the upgrade workflow to view upgrade recommendations and a summary of new features available in your target ONTAP release.

=== Valuable insights
You can view the summary of the benefits that you received through Active IQ and your support contract. For selected systems, the value report consolidates the  benefits from last one year.

=== Drill into details
Provides deeper information, which is a powerful way to dig deeper into the data and gain immediate insights into the make-up of aggregated information as required.

=== Capacity additions
You can proactively identify systems that have exceeded capacity or are nearing 90% capacity and send a request to increase capacity.

== 29 February 2020
This update includes the following new features and enhancements:

=== Enhanced user interfaces
The latest Active IQ Digital Advisor Dashboards offer a personalized experience. It allows smooth and seamless navigation, with its intuitiveness, throughout different dashboards, widgets, and screens. It provides an	all-in-one experience. It communicates comparisons, relationships, and trends. It provides insights that help you detect and validate important relationships and meaningful differences based on the data that is presented by different dashboards.

=== Customizable dashboards
Helps you monitor your systems at a glance by providing key insights and analysis about your data on one or more pages or screens. You can also create up to 10 dashboards and make effective business decisions.

=== Mitigate risks using Active IQ Unified Manager
You can view the risks and rectify them by using Active IQ Unified Manager.

=== Wellness
Provides detailed information about the status of your storage system that is classified into the following 6 widgets:
[disc]
* Performance & Efficiency
* Availability & Protection
* Capacity
* Configuration
* Security
* Renewals

=== Smarter and faster search
Allows you to search parameters, such as serial number, system ID, host name, site name, group name, and cluster name using the single-system view. You can also search for group of systems, in addition, you can search by a customer name, site name, or group name by group of systems.
