---
sidebar: sidebar
permalink: reference_aiq_faq.html
keywords: faq, frequently asked questions, non-technical, non-technical case, inventory, storage efficiency, capacity, performance
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions about Digital Advisor
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The following questions give answers to your frequent queries about Digital Advisor.

== Non-technical case

*What is a non-technical case?*

Issues such as unable to view systems in the inventory, incorrect contract term dates, and so on, which are not technical in nature are classified as non-technical cases.

*When do I need to create a non-technical case?*

A non-technical case should be created for the following cases:

* Unable to access certain features
* Missing systems in inventory
* Decommissioning a system from the install base
* Incorrect or missing contract term dates
* Incorrect support offering

*How do I create a non-technical case?*

. Click link:https://mysupport.netapp.com/site/help[here^] to open the “Non-Technical Feedback Tool" on the NetApp Support site.
. Select the appropriate category from the *Feedback Category* drop-down list.
. Enter the required details and provide additional information in the “Comments” box”.
. Click *Submit*.

A case is created, and a case number is provided for your reference.

*How do I provide feedback or ask other questions related to Digital Advisor?*

To provide feedback or ask questions, send an email to mailto:ng-activeiq-feedback@netapp.com[[.underline]#ng-activeiq-feedback@netapp.com#].

== Storage efficiency

*How do I access Storage Efficiency in Digital Advisor?*

. Open the home page of link:https://activeiq.netapp.com/?source=onlinedocs[Digital Advisor^].
. Search for a customer, site, group, cluster, or node from the top right search box to reach the respective dashboard.
. Click *Storage Efficiency* from the left navigation.

NOTE: The dashboards created using a watchlist will not be displayed in the Storage Efficiency widget.

*Does Digital Advisor display ratios for all ONTAP systems?*

Digital Advisor displays ratios for systems running ONTAP 9.1 and later.

*What is the ‘With Snapshots copies’ toggle on the efficiency dashboard?*

The Digital Advisor Efficiency Dashboard calculates the data reduction ratio at multiple levels, including customer, site, group, cluster, and node. If you turn on the *With Snapshots copies* toggle, the data reduction ratio calculation includes the following storage efficiency technologies:

  * Deduplication
	* Compression
	* Data compaction
	* Clones
  * Snapshots 

By default, the data reduction ratio calculation does not include Snapshots storage efficiency technology.

*What is physical data used and logical data used?*

* Physical Blocks Consumed / Physical Data Used
** The amount of space being used for data now (rather than being reserved for future use)
** Includes space used by aggregate Snapshot copies
** Space actually consumed/written by the client

* Total Logical Data Used
** Displays the logical size used in the aggregate.
** This includes Volumes, Clones, and Snapshots in the aggregate.
** The logical size is computed based on physical usage (real writes) and savings obtained in the aggregate.
** Does not include space reserved for future use

*Which AutoSupport instances are used for calculating data reduction ratio?*

Calculations are performed using either the latest weekly or user-triggered AutoSupport instances which tend to contain most of the sections required for calculating the ratio.

*Which volumes or aggregates are excluded from data reduction calculation?*

The following objects are not considered while calculating data reduction ratio:

* Root aggregates
* Offline volumes
* Vserver root/admin root volumes
* MCC configuration volumes

*How can I see the trend in data reduction ratio?*

Currently, data reduction ratio is calculated based on the latest weekly or user-triggered AutoSupport instance. The trending may be considered for a future release.

*How are customer-level ratios and data reduction savings calculated?*

Customer-level storage efficiency dashboard provides the data reduction ratio with and without Snapshot copies for AFF and non-AFF systems and are combined across the customer installed base for systems running ONTAP 9.1 and later. The required parameters for the following calculations are taken from ONTAP AutoSupport:

Without Snapshot copies (calculated for per Aggr first):

[%autowidth, indent=8]
|===
    |*Operation*  | *Formula*

    |Aggr Logical Used without Snapshot copies | Logical Size Used by Volumes, Clones, Snapshot Copies in the Aggregate – Logical Size Used by Snapshot Copies
    |Aggr Physical Used Without Snapshot copies | Total Physical Used – (Physical Size Used by Snapshot copies / Aggregate Data Reduction Ratio)
    |Customer Efficiency Ratio without Snapshot copies | Sum [Aggr Logical Used without Snapshot copies for all aggregates and for all nodes of a customer] / Sum [Aggr Physical Used without Snapshot copies for all aggregates and for all nodes of a customer] : 1
|===

With Snapshot copies:

[%autowidth, indent=8]
|===
    |*Operation*  | *Formula*

    |Customer Logical Size with Snapshot copies | Sum [Logical Size Used by Volumes, Clones, Snapshot copies for all aggregates and for all nodes of a customer]
    |Customer Physical Size Used with Snapshot copies | Sum [Total Physical Size Used for all aggregates and for all nodes of a customer]
    |Customer Efficiency Ratio with Snapshot copies | Customer Logical Size with Snapshot copies and Clones / Customer Physical Size Used with Snapshot copies and Clones : 1
|===

Efficiency feature table calculations:

[%autowidth, indent=8]
|===
    |*Operation*  | *Formula*

    |Customer Physical Space Used | Sum of Physical Space Used by the Aggregate for all aggregates and of all nodes of a customer
    |Customer Logical Size Used without Snapshot copies | Sum of Logical Size Used by Volumes, Clones, Snapshot Copies - Logical Size Used by Snapshot copies for all aggregates of all nodes of a customer
    |Customer Logical Size Used with Snapshot copies | Sum of Logical Size Used by Volumes, Clones, Snapshot Copies in the Aggregate for all aggregates of all nodes of a customer
		|Total Space Saved | Total Logical Space Used – Total Physical Space Used
    |Deduplication Savings | Sum of Space Saved by Volume Deduplication + Space Saved by Inline Zero Pattern Detection of each aggregate of all nodes of a customer
		|Compression Savings | Sum of Space Saved by Volume Compression of each aggregate of all nodes of a customer
		|Compaction Savings (for ONTAP 	9.1) | Sum of Space Saved by Aggregate Compaction of each aggregate of all nodes of a customer
    |Compaction Savings (for ONTAP 	9.2 and later) | Sum of Space Saved by Aggregate Data Reduction of each aggregate of all nodes of a customer
		|FlexClone Savings | Sum of (Logical Size Used by FlexClone Volumes - Physical Sized Used by FlexClone Volumes) of each aggregate of all nodes of a customer
    |Snapshot copies Backup Savings | Sum of (Logical Size Used by Snapshot copies - Physical Size Used by Snapshot copies) of all aggregates of all nodes of a customer
|===

*Why does adding all individual data reduction savings not add up to data reduction savings?*

Data reduction savings are shown in the Storage Efficiency dashboard for volumes and local tiers (aggregates).  You cannot add volume savings and aggregate savings as they both happen at different storage objects.

*Why was data reduction reported as higher or incorrect before upgrading to ONTAP?*

Data reduction is shown higher when data protection volumes are present in the node due to a bug in ONTAP. The issue was fixed in ONTAP 9.3P11. Storage Efficiency reports correct or lower values when upgraded from ONTAP versions earlier than 9.3P11 and when data protection volumes are present in the node.

== Inventory

*Why cannot I find certain systems in Digital Advisor?*
You may not be able to search for certain systems or view them in inventory page due to one of the following reasons:

* New systems take over a day to reflect in Digital Advisor once they are added or updated in SAP.
* The systems are secure and you are not authorized to view the secure systems.
* You are not entitled to view the systems.
* Systems are inactive, archived, or decommissioned in SAP.

If you are unable to view systems for any other reasons, have queries, or wish to request for access, link:https://mysupport.netapp.com/site/help[create a non-technical case^]. To learn more about non-technical case, click <<Non-technical case,here.>>

== Capacity

*How are capacities calculated in Digital Advisor?*
The capacities in Digital Advisor are calculated for cluster and node — excluding root and including Snapshot copies
[%autowidth, indent=10]
|===
    |*Capacity*  | *Calculated by adding each aggregate…*

    |Raw Capacity | All Phys (MB/blks) of “SYSCONFIG -R"
    |Usable Capacity | Kbytes (Allocated) of "DF -A"
    |Used Capacity (with Reserve) | Used of   “DF -A”
    |Available Capacity | Avail of “DF -A”
    |Physical Capacity (Actual)| Total Physical Used of “AGGR-EFFICIENCY.XML”
    |Logical Capacity (Effective)| Logical Size Used by Volumes, Clones, and Snapshot copies in the Aggregate of “AGGR-EFFICIENCY.XML”
|===

*For Local tier (Aggregate with Snapshot copies)*
[%autowidth, indent=10]
|===
    |*Capacity*  | *Calculated by using…*

    |Usable Capacity | Kbytes (allocated) of "DF -A"
    |Used Capacity (with Reserve) | Used of   “DF -A”
    |Available Capacity| Avail of “DF -A”
    |Physical Capacity (Actual)| Total Physical Used of “AGGR-EFFICIENCY.XML”
    |Logical Capacity (Effective)| Logical Size Used by Volumes, Clones, and Snapshot copies in the Aggregate of “AGGR-EFFICIENCY.XML”
|===

*For Volume (Volume with Snapshot copies)*
[%autowidth, indent=10]
|===

    |*Capacity*  | *Calculated by using…*

    |Volume Capacity | Volume Size of “VOLUME.XML”
    |Used Capacity (with Reserve) | Used Size of "VOLUME.XML"
    |Available Capacity| Available Size of “VOLUME.XML”
    |Physical Capacity (Actual)| Total Physical Used of “VOL STATUS -S”
    |Logical Capacity (Effective)| Logical Used Size of “VOLUME.XML”
|===

*What are Physical Capacity (Actual), Logical Capacity (Effective), and Used Capacity (with Reserve)?*

* Physical Blocks Consumed/Physical Capacity Used (Actual)
** The amount of space being used for data now (rather than being reserved for future use)
** Includes space used by aggregate Snapshot copies
** Space actually consumed or written by the client

* Logical Capacity (Effective) Logical Data Used
** Displays the logical size used in the aggregate
** The aggregate incudes Volumes, Clones, and Snapshot copies.
** The logical size is computed based on physical usage (real writes) and savings obtained in the aggregate.

NOTE:	It does not include space reserved for future use.

* Total Data Used/Used Capacity (with Reserve)
** The sum of all space used or reserved in the aggregate by volumes, metadata, or Snapshot copies

NOTE: It includes space reserved for volumes that are of file or volume guarantee type. It includes delayed frees, aggr blog, and metadata in addition to reserves. It shows up as used space until the delayed free blocks are purged. After it is purged, the used space decreases.

*How is the Capacity Forecast calculated?*
The Capacity Forecast uses used capacity data over the last year to calculate the average weekly growth rate of a system. This rate of change in system usage is then extrapolated forward from the current used capacity, to demonstrate how system utilization is expected to change over the next 6 months (assuming  the total usable capacity remains the same).

*Why does added Used Capacity of each volume not match the aggregated Used Capacity at the node level?*
Used Capacity at the node level includes space reserved by volumes, metadata, and Snapshot copies. It also includes space reserved for volumes—file or volume guarantee type. Hence, both might not match.

*Are Capacities shown in Digital Advisor Base 2 or Base 10?*
All capacities displayed in Digital Advisor are Base 2 (divide by 1024) and represent capacities in GiB/TiB. ONTAP storage and other NetApp products also display capacity usage in Base 2.

For StorageGRID, capacities are displayed in Base 10 and the unit of capacity is expressed in TB.

