---
sidebar: sidebar
permalink: reference_limitations_activeiq.html
keywords: limitation, issues, not supported, drawbacks
summary: Provides information about the limitations in the release.
---

= Known limitations
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

The following limitations exist:

* For Data ONTAP storage systems operating in 7-Mode only (Data ONTAP storage systems operating in 7-Mode is nearing End of Support Life)
** Performance charts
** Storage efficiency
* Upgrade Advisor will not support upgrade plans for clustered ONTAP earlier than 9.0.

== Editing a watchlist may take 60 minutes to reflect in Active IQ Digital Advisor
Editing a watchlist does not update the information in Active IQ Digital Advisor immediately. It may take up to 60 minutes for the changes to reflect in Active IQ Digital Advisor.

== A blank report is displayed while scheduling reports
Scheduled reports are available only with a SupportEdge Advisor or a SupportEdge Expert support contract. If your systems are not under SupportEdge Advisor or a SupportEdge Expert support contract, you may get a blank report while scheduling reports.
