---
sidebar: sidebar
permalink: reference_limitations_activeiq.html
keywords: limitation, issues, not supported, drawbacks
summary: Provides information about the limitations in the release.
---

= Known limitations
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

=== Limited support for Value Report
The Valuable Insights widget provides high level information about the storage system. It is only available on the Dashboard and does not have any drill down details.

=== Differences in features between Active IQ Classic and Active IQ Digital Advisor
The following features which exist in Active IQ Classic are not planned to be added in Active IQ Digital Advisor due to low usage (unless otherwise noted):

* For ONTAP 7-Mode systems only (7-mode is nearing End of Support Life)
** Upgrade Advisor - also deprecating clustered ONTAP < 9.0
** Performance charts
** Storage efficiency
* Performance Charts (see above for 7-mode) (Most of the features have been moved to Active IQ Digital Advisor)
** Node Headroom Confidence Factor
** Node Disk Throughput
** Cluster CPU Utilization
** Cluster Latency
** Cluster Disk Throughput
* Event History (ONTAP node dashboard)
* Flash Advisor
* Cloud Control Recommendations
* AutoSupport Notifications
* AutoSupport Alerts – some of the features will be merged with wellness actions and risks
* Protection Advisor – part of this will be available in Data Center Viewer
* Performance charts supporting guarantee program - this is being supported by AIQ Unified Manager

The following features which exist in Active IQ Classic will also be available soon in Active IQ Digital Advisor:

* FabricPool Advisor
* Wellness actions history & trending
* Notifications
* Cluster Viewer reporting
* Scheduled report for capacity and efficiency
* Workload tagging
* Peak performance graph for Aggregate utilization
* Download performance Reports in PNG/JPG format
* Newsletter Subscriptions
* Downloading Value Report details
