---
sidebar: sidebar
permalink: reference_limitations_activeiq.html
keywords: limitation, issues, not supported, drawbacks
summary: Provides information about the limitations in the release.
---

= Known limitations
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

=== Limited support for wellness (risk assessment)
You cannot acknowledge a risk or view the details of the risk from the risk page. For more information about the risk or the process to acknowledge the risk, see the Active IQ documentation.

=== Limited support for ClusterViewer
The ClusterViewer feature only provides information about the summary of the clusters and the storage information at a cluster level.

=== Limited support for Value Report
This Valuable insights widget provides high level information about the storage system. It is only available on the Dashboard and does not have any drill down details.

=== Limited support for Upgrade Advisor
The upgrade workflow is not complete; please utilize the Upgrade Advisor workflow in Active IQ to generate upgrade plans.
