---
sidebar: sidebar
permalink: reference_new_activeiq.html
keywords: what's new, features, new
summary: Provides information about the new features in the release.
---

= What's new in Active IQ Digital Advisor
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The following features and enhancements have been introduced in NetApp Active IQ Digital Advisor:

== 16 August 2021

=== Wellness Review
You can now generate the on-demand report. In addition, you can download the last scheduled report from the Wellness Review Subscription screen.

=== Inventory
In the Grid Inventory tab, you can now view the node details based on site level in an expandable and collapsible format.

== 12 July 2021

=== System Firmware
You can now view information about the system firmware that is shipped along with the major and patch versions of ONTAP. You can access this feature from the Quick Links menu.

=== Health Check Dashboard

* The Health Check Dashboard has been enhanced to include a blue banner notifying users that the systems that are not supported by SupportEdge Advisor and SupportEdge Expert will not be factored in while calculating the health score.
* The Recommended Configuration widget has been enhanced to provide an in-depth analysis of the failed checks for your storage VM (SVM) and lets you take the recommended corrective actions for each risk.
* The recommended target ONTAP version is now the same for all nodes in a cluster configured with different hardware models. The target version is supported on all the nodes.
* You can now extend the EOS timeline for controllers, disks, and shelves through the purchase of a PVR. PVR dates and extension details, when purchased, are viewable in the end-of-support widget. The PVR details are also provided as part of the EOSL report.

=== Inventory
You can view the end dates of the support contracts for your hardware, software, and non-returnable disks on the detailed inventory page.

=== Support Offering Upgrade

* The user interface has been enhanced to display the specific support offering that you are subscribed to in Active IQ.
* You can now raise a request to upgrade your support offering subscription from the system dashboard to access more features.

== 25 June 2021

=== Flex Subscription widget

* If you have opted for ONTAP Collector to obtain data on your capacity usage, you can view the details of your file shares and disks in the Shares and Disks tabs. You can save storage space by identifying those nearing committed capacity.
* The capacity usage, shown on the Keystone - Capacity Utilization dashboard and used for billing, is now based on the logical capacity.

== 17 June 2021

=== Reports
You can now generate aggregate volume performance reports for all volumes in a storage VM for any day, week, or month.

=== Wellness review email
The wellness review email has been enhanced to include information about the support and entitlements from the health check and upgrade actions.

=== Upgrade workflow

* The user interface has been enhanced to provide you with a table view of the information.
* You can now view information about the end of support of the ONTAP version in the Upgrade Details screen.

=== Config Drift

* Config Drift now supports over 200 AutoSupport sections for creating golden templates and generating drift reports across customer, site, group, watchlist, cluster, and host.
* Config drift allows you to mitigate deviations using Ansible playbooks which are included in the config drift report payload.

=== Health Check Assessment Dashboard
This feature has been enhanced to compare your storage VM (SVM) against a predefined catalog of risks to assess gaps and recommend the associated corrective actions.

== 09 June 2021

=== Health Check Assessment Dashboard
You can now view the number of systems based on which the health score is calculated. This enhancement is applicable for all the attributes in the Health Check Assessment Dashboard.

== 20 May 2021

=== Drift Chat for capacity addition requests
For real-time assistance on your capacity addition requests, chat with a salesperson directly from your dashboard. link:task_identify_capacity_system.html[Learn how].

== 29 April 2021

* Here's how to protect your systems against hackers and Ransomware attacks. link:task_increase_protection_against_hackers_and_Ransomware_attacks.html[Learn how].
* You can avoid the downtime and possible data loss. link:task_avoid_the_downtime_and_possible_data_loss.html[Learn how].
* Learn how to avoid a volume filling up to prevent an outage. link:task_avoid_a_volume_filling_up_to_prevent_an_outage.html[Learn how].

== 07 April 2021

=== Watchlist
When you access Active IQ Digital Advisor for the first time, you should now create a watchlist instead of a dashboard. You can also view the dashboard for different watchlists, edit the details of an existing watchlist, and delete a watchlist.

== 24 February 2021

=== Config Drift

This release provides the following functionality:

* Ability to edit attributes during template creation.
* Grouping of AutoSupport sections.
* Generate or schedule a config drift report across customer, site, group, watchlist, cluster, and hostname. link:task_compare_config_drift_template.html[Learn how].

=== Reports
You can generate or schedule Capacity and Efficiency reports to view detailed information on the capacity and storage efficiency savings of your system.

== 10 February 2021

=== StorageGRID
StorageGRID Dashboard is enabled using the NextGen API framework.

You can use the StorageGRID Dashboard for viewing information at the Watchlist, Customer, Group, and Site level.

This release provides the following functionality:

* *Inventory widget:* View inventory of StorageGRID systems available under the selected level.
* *Wellness widget:* View all the Risks and Actions, including the ones related to StorageGRID if they are applicable based on existing ARS rules for the available systems.
* *Planning widget:*
** *Capacity Addition:* For any GRID sites that are exceeding the threshold of 70% of existing capacity, you’ll be notified. You have the option to add capacity for the StorageGRIDs in the site, for the next 1, 3, & 6 months if the capacity threshold is likely to exceed 70%.
** *Renewals:* For any StorageGRID systems for which the license contract has expired or is nearing expiration in the next 6 months, you’ll be notified. You can select one or more systems to raise a request to the NetApp support team for renewal.
* *GRID dashboard:* The GRID dashboard provides wellness, planning, and configuration details for the selected GRID.
* *Configuration widget:* Provides basic details of the selected StorageGRID in the widget, such as GRID Name, Host Name, Serial Number, Model, OS Version, Customer Name, Shipped Location, and Contact Details.
* *GRID Viewer:* From the *Configuration* widget, you can view the GRID configuration in detail by clicking the *GRID Viewer* link. From the *Configuration* widget, you can download the Site Details and Capacity Details for the selected StorageGRID by clicking the *Download* button in the *Grid Viewer* screen.
* *Site details:* This tab provides the Grid Summary and Storage Nodes available for each site.
* *GRID summary:* Contains basic information, such as License Type, License Capacity, number of installed nodes, Support Term (Date of termination of license contract), Primary Admin Node, and Primary Site of the Primary Admin Node. This tab also provides the Site name and the number of storage nodes tagged under the corresponding site. In this release, you can view the list of node names upon clicking the hyperlink available for viewing storage nodes for the corresponding site.
* *Capacity Details tab:* Provides the Grid Level and Site capacity details configured for the GRID. The Capacity details, such as Installed Storage Capacity, Available Storage Capacity, Total Used Storage Capacity, and Capacity used for Data and Metadata. These details are available at both the Grid and Site levels.

=== FabricPool Advisor
The Tier Data button has been added to the FabricPool dashboard, and it lets you tier data to low-cost object storage tiers using NetApp Cloud Manager.

=== Cloud ready workloads
You can view the different types of workloads that are available within your storage system and identify the workloads that are cloud-ready.

== 21 December 2020

=== Health Check Assessment Dashboard
The following widgets have been added to the dashboard:

* Recommended Software:  This widget provides a consolidated list of all the software and firmware upgrades and currency recommendations.
* Loss of Signal: This widget provides scores and information about the systems, which have stopped sending AutoSupport data for some reason. It provides information if no AutoSupport data has been received from a hostname within a 7-day period.

== 12 November 2020

=== Integrating data using APIs
You can use Active IQ APIs to pull data of interest and integrate it directly into your company’s workflow. link:concept_overview_API_service.html[Learn more].

=== Wellness - Upgrades widget
The enhanced Risk Advisor and Upgrade Advisor tabs enable you to view all the system risks and help you plan for an upgrade for mitigating all the risks.

=== Health Check Assessment Dashboard
The Recommended Configuration widget has been added to the dashboard, and it provides a summary on the number of systems that are monitored for remote management risks, spares and failed drives risks, and HA pair risks.

=== FabricPool Advisor
You can reduce your storage footprint and associated costs by monitoring your clusters, which have been classified into four categories: inactive local tier (aggregate) data, inactive volume data, tiered data, and those that are not IDR enabled.

=== Localization in Simplified Chinese and Japanese
Active IQ Digital Advisor is now available in three languages – Chinese, English, and Japanese.

=== Reports
You can generate or schedule ClusterViewer reports to view detailed information on the physical and logical configuration of your systems. link:task_generate_reports.html[Learn how].

== 15 October 2020

=== Health Check Assessment Dashboard
The Active IQ Health Check Assessment (HCA) Dashboard provides a point-in-time review of your overall environment. Based on the health check score, you can align your storage systems to the recommended NetApp best practices to facilitate longer-term planning and improve the health of your installed base. link:concept_understand_health_check_assessment_dashboard.html[Learn more].

=== Config Drift
This feature enables you compare the system and cluster configurations and the detect configuration deviations in near real time. link:task_add_config_drift_template.html[Learn how to add a config drift template].

=== AutoSupport
You can view your AutoSupport data and review the details.

=== Wellness Review Subscription
You can subscribe to receiving monthly email notifications that summarize wellness status of systems—that are nearing their renewal dates and require an upgrade for the NetApp products in your installed base. link:task_subscribe_to_wellness_review_email.html[Subscribe now].

=== Reports
You can use the reports feature to generate reports immediately or schedule a report to be generated on a weekly or monthly basis. link:task_generate_reports.html[Learn how].

=== Manual AutoSupport Upload
Manual AutoSupport Upload has been enhanced to improve the user experience. An additional column has been provided for remarks on the upload status.

=== Flex Subscription widget
You can monitor the committed, consumed, and burst storage capacity for your NetApp Keystone Flex Subscription Service.

== 30 September 2020

=== AFF and FAS firmware using Ansible Playbook
The documentation has been enhanced to include information about downloading, installing, and executing the AFF and FAS firmware ansible automation package.

link:task_update_AFF_FAS_firmware.html[Learn how to update AFF and FAS firmware using Ansible Playbook].

== 18 August 2020

=== Performance
Performance graphs have been enhanced to enable you to assess the performance of the volume. You can navigate and toggle between the node tab, cluster tab, the local tier tab, and the volume tab on the same screen. link:task_view_performance_graphs.html[Learn how].

=== AFF and FAS firmware using Ansible Playbook
The AFF and FAS firmware screen has been enhanced to provide a better user experience.

== 17 July 2020

=== Performance
Performance graphs have been enhanced to enable you to assess the performance of the local tier. You can navigate and toggle between the node tab, cluster tab, and the local tier tab on the same screen.

=== Wellness
The wellness attributes have been enhanced to view all the affected systems without having to drill-down to the actions and risks.

== 19 June 2020

=== Generate report for inventory
You can now generate report of the selected watchlist and emails the report to a maximum of 5 recipients. link:task_view_inventory_details.html[Learn how].

=== Performance
Performance graphs have been enhanced to enable you to assess the cluster performance of your storage system. You can navigate and toggle between the node tab and the cluster tab on the same screen.

=== Storage efficiency
The storage efficiency widget has been enhanced to enable you to view the storage efficiency ratio and savings at a cluster level. You can navigate and toggle between the node tab and the cluster tab on the same screen.

=== Update the default home page
You can now provide your feedback and let us know the reason you are updating the default home page screen for Active IQ.

=== Update to the inventory widget
The inventory widget has been enhanced to improve the user experience, by providing user-friendly date formats, additional columns for end of platform support and end of version support.

== 19 May 2020

=== Set the default home page
You can now set the default home page screen for Active IQ. You can either set it to Active IQ Digital Advisor or Active IQ Classic.

=== Storage efficiency
You can view the storage efficiency ratio and savings of your storage system with and without Snapshot backups for AFF systems, non-AFF systems, or both. You can view the storage efficiency information at a node level. link:task_analyze_storage_efficiency.html[Learn how].

=== Performance
Performance graphs enable you to assess the performance of your storage devices in different significant areas.

=== AFF and FAS firmware upgrades using Ansible Playbook
Update the AFF and FAS firmware using Ansible on your storage system to mitigate the identified risks and to keep your storage system up to date.

=== Disabling the wellness score feature
The wellness score feature is being temporarily disabled to improve the scoring algorithm and simplify the overall experience.

== 02 April 2020

=== Onboarding overview video
The onboarding video helps users to quickly get familiar with the options and features of Active IQ Digital Advisor.

=== Wellness score
Wellness score provides customers with a consolidated score of their installed base based on the number of high risks and the expired contracts. Score can be good, average, or poor.

=== Risk summary
The risk summary provides detailed information about the risk, the impact of the risk, the corrective actions.

=== Support for acknowledging and disregarding risks
Provides the option to acknowledge a risk if you do want to mitigate or are unable to mitigate the risk.

== 19 March 2020

=== Upgrade workflow
You can use the upgrade workflow to view upgrade recommendations and a summary of new features available in your target ONTAP release. link:task_view_upgrade.html[Learn how].

=== Valuable insights
You can view the summary of the benefits that you received through Active IQ and your support contract. For selected systems, the value report consolidates the benefits from last one year. link:task_view_valuable_insight_widget.html[View now].

=== Drill into details
Provides deeper information, which is a powerful way to dig deeper into the data and gain immediate insights into the make-up of aggregated information as required.

=== Capacity additions
You can proactively identify systems that have exceeded capacity or are nearing 90% capacity and send a request to increase capacity.

== 29 February 2020

=== Enhanced user interfaces
The latest Active IQ Digital Advisor Dashboards offer a personalized experience. It allows smooth and seamless navigation, with its intuitiveness, throughout different dashboards, widgets, and screens. It provides an	all-in-one experience. It communicates comparisons, relationships, and trends. It provides insights that help you detect and validate important relationships and meaningful differences based on the data that is presented by different dashboards.

=== Customizable dashboards
Helps you monitor your systems at a glance by providing key insights and analysis about your data on one or more pages or screens. You can also create up to 10 dashboards and make effective business decisions.

link:concept_overview_dashboard.html[Learn more].

=== Mitigate risks using Active IQ Unified Manager
You can view the risks and rectify them by using Active IQ Unified Manager. link:task_view_risks_remediated_unified_manager.html[Learn how].

=== Wellness
Provides detailed information about the status of your storage system that is classified into the following 6 widgets:
[disc]
* Performance & Efficiency
* Availability & Protection
* Capacity
* Configuration
* Security
* Renewals

See link:concept_overview_wellness.html[Analyze wellness attributes] for more details.

=== Smarter and faster search
Allows you to search parameters, such as serial number, system ID, host name, site name, group name, and cluster name using the single-system view. You can also search for group of systems, in addition, you can search by a customer name, site name, or group name by group of systems.
