---
sidebar: sidebar
permalink: reference_limitations_activeiq.html
keywords: limitation, issues, not supported, drawbacks
summary: Provides information about the limitations in the release.
---

= Known limitations
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

=== Low Impact Risks and Best Practices Removed
To help you take the best action for improving the wellness of your installed base, we have removed the low impact risks and best practice checks, except in areas such as storage efficiency. We urge you to review and mitigate high and medium impact risks at the earliest to ensure the highest levels of availability and optimization for your NetApp installed base.

=== Limited support for ClusterViewer
The ClusterViewer feature only provides information about the summary of the clusters and the storage information at a cluster level.

=== Limited support for Value Report
This Valuable insights widget provides high level information about the storage system. It is only available on the Dashboard and does not have any drill down details.

=== Limited support for Upgrade Advisor
The upgrade workflow is not complete; please utilize the Upgrade Advisor workflow in Active IQ to generate upgrade plans.
