---
sidebar: sidebar
permalink: reference_new_activeiq.html
keywords: what's new, features, new
summary: Provides information about the new features in the release.
---

= What's new in Active IQ Digital Advisor
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Active IQ typically introduces a new release every month to bring you the new features and enhancements.

== 21 December 2020
This update includes the following new features, enhancements, and changes:

=== Health Check Assessment Dashboard
The following widgets have been added to the dashboard:

* Recommended Software:  This widget provides a consolidated list of all the software and firmware upgrades and currency recommendations.
* Loss of Signal: This widget provides scores and information about the systems, which have stopped sending AutoSupport data for some reason. It provides information if no AutoSupport data has been received from a hostname within a 7-day period.

== 12 November 2020
This update includes the following new features, enhancements, and changes:

=== Integrating data using APIs
You can use Active IQ APIs to pull data of interest and integrate it directly into your company’s workflow. link:concept_overview_API_service.html[Learn more].

=== Wellness - Upgrades widget
The enhanced Risk Advisor and Upgrade Advisor tabs enable you to view all the system risks and help you plan for an upgrade for mitigating all the risks.

=== Health Check Assessment Dashboard
The Recommended Configuration widget has been added to the dashboard, and it provides a summary on the number of systems that are monitored for remote management risks, spares and failed drives risks, and HA pair risks.

=== FabricPool Advisor
You can reduce your storage footprint and associated costs by monitoring your clusters, which have been classified into four categories: inactive local tier (aggregate) data, inactive volume data, tiered data, and those that are not IDR enabled.

=== Localization in Simplified Chinese and Japanese
Active IQ Digital Advisor is now available in three languages – Chinese, English, and Japanese.

=== Reports
You can generate or schedule ClusterViewer reports to view detailed information on the physical and logical configuration of your systems. link:task_generate_reports.html[Learn how].

== 15 October 2020
This update includes the following new features, enhancements, and changes:

=== Health Check Assessment Dashboard
The Active IQ Health Check Assessment (HCA) Dashboard provides a point-in-time review of your overall environment. Based on the health check score, you can align your storage systems to the recommended NetApp best practices to facilitate longer-term planning and improve the health of your installed base. link:concept_understand_health_check_assessment_dashboard.html[Learn more].

=== Config Drift
This feature enables you compare the system and cluster configurations and the detect configuration deviations in near real time. link:task_add_config_drift_template.html[Learn how to add a config drift template].

=== AutoSupport
You can view your AutoSupport data and review the details.

=== Wellness Review Subscription
You can subscribe to receiving monthly email notifications that summarize wellness status of systems—that are nearing their renewal dates and require an upgrade for the NetApp products in your installed base. link:task_subscribe_to_wellness_review_email.html[Subscribe now].

=== Reports
You can use the reports feature to generate reports immediately or schedule a report to be generated on a weekly or monthly basis. link:task_generate_reports.html[Learn how].

=== Manual AutoSupport Upload
Manual AutoSupport Upload has been enhanced to improve the user experience. An additional column has been provided for remarks on the upload status.

=== Keystone
You can monitor your committed, consumed, and burst storage capacity using Keystone.

== 30 September 2020
This update includes the following new features, enhancements, and changes:

=== AFF and FAS firmware using Ansible Playbook
The documentation has been enhanced to include information about downloading, installing, and executing the AFF and FAS firmware ansible automation package.

link:task_update_AFF_FAS_firmware.html[Learn how to update AFF and FAS firmware using Ansible Playbook].

== 18 August 2020
This update includes the following new features, enhancements, and changes:

=== Performance
Performance graphs have been enhanced to enable you to assess the performance of the volume. You can navigate and toggle between the node tab, cluster tab, the local tier tab, and the volume tab on the same screen. link:task_view_performance_graphs.html[Learn how].

=== AFF and FAS firmware using Ansible Playbook
The AFF and FAS firmware screen has been enhanced to provide a better user experience.

== 17 July 2020
This update includes the following new features, enhancements, and changes:

=== Performance
Performance graphs have been enhanced to enable you to assess the performance of the local tier. You can navigate and toggle between the node tab, cluster tab, and the local tier tab on the same screen.

=== Wellness
The wellness attributes have been enhanced to view all the affected systems without having to drill-down to the actions and risks.

== 19 June 2020
This update includes the following new features, enhancements, and changes:

=== Generate report for inventory
You can now generate report of the selected watchlist and emails the report to a maximum of 5 recipients. link:task_view_inventory_details.html[Learn how].

=== Performance
Performance graphs have been enhanced to enable you to assess the cluster performance of your storage system. You can navigate and toggle between the node tab and the cluster tab on the same screen.

=== Storage efficiency
The storage efficiency widget has been enhanced to enable you to view the storage efficiency ratio and savings at a cluster level. You can navigate and toggle between the node tab and the cluster tab on the same screen.

=== Update the default home page
You can now provide your feedback and let us know the reason you are the updating the default home page screen for Active IQ.

=== Update to the inventory widget
The inventory widget has been enhanced to improve the user experience, by providing user-friendly date formats, additional columns for end of platform support and end of version support.

== 19 May 2020
This update includes the following new features, enhancements, and changes:

=== Set the default home page
You can now set the default home page screen for Active IQ. You can either set it to Active IQ Digital Advisor or Active IQ Classic.

=== Storage efficiency
You can view the storage efficiency ratio and savings of your storage system with and without Snapshot backups for AFF systems, non-AFF systems, or both. You can view the storage efficiency information at a node level. link:task_analyze_storage_efficiency.html[Learn how].

=== Performance
Performance graphs enable you to assess the performance of your storage devices in different significant areas.

=== AFF and FAS firmware upgrades using Ansible Playbook
Update the AFF and FAS firmware using Ansible on your storage system to mitigate the identified risks and to keep your storage system up to date.

=== Disabling the wellness score feature
The wellness score feature is being temporarily disabled to improve the scoring algorithm and simplify the overall experience.

== 02 April 2020
This update includes the following new features and enhancements:

=== Onboarding overview video
The onboarding video helps users to quickly get familiar with the options and features of Active IQ Digital Advisor.

=== Wellness score
Wellness score provides customers with a consolidated score of their installed base based on the number of high risks and the expired contracts. Score can be good, average, or poor.

=== Risk summary
The risk summary provides detailed information about the risk, the impact of the risk, the corrective actions.

=== Support for acknowledging and disregarding risks
Provides the option to acknowledge a risk if you do want to mitigate or are unable to mitigate the risk.

== 19 March 2020
This update includes the following new features and enhancements:

=== Upgrade workflow
You can use the upgrade workflow to view upgrade recommendations and a summary of new features available in your target ONTAP release. link:task_view_upgrade.html[Learn how].

=== Valuable insights
You can view the summary of the benefits that you received through Active IQ and your support contract. For selected systems, the value report consolidates the benefits from last one year. link:task_view_valuable_insight_widget.html[View now].

=== Drill into details
Provides deeper information, which is a powerful way to dig deeper into the data and gain immediate insights into the make-up of aggregated information as required.

=== Capacity additions
You can proactively identify systems that have exceeded capacity or are nearing 90% capacity and send a request to increase capacity.

== 29 February 2020
This update includes the following new features and enhancements:

=== Enhanced user interfaces
The latest Active IQ Digital Advisor Dashboards offer a personalized experience. It allows smooth and seamless navigation, with its intuitiveness, throughout different dashboards, widgets, and screens. It provides an	all-in-one experience. It communicates comparisons, relationships, and trends. It provides insights that help you detect and validate important relationships and meaningful differences based on the data that is presented by different dashboards.

=== Customizable dashboards
Helps you monitor your systems at a glance by providing key insights and analysis about your data on one or more pages or screens. You can also create up to 10 dashboards and make effective business decisions.

link:concept_overview_dashboard.html[Learn more].

=== Mitigate risks using Active IQ Unified Manager
You can view the risks and rectify them by using Active IQ Unified Manager. link:task_view_risks_remediated_unified_manager.html[Learn how].

=== Wellness
Provides detailed information about the status of your storage system that is classified into the following 6 widgets:
[disc]
* Performance & Efficiency
* Availability & Protection
* Capacity
* Configuration
* Security
* Renewals

See link:concept_overview_wellness.html[Analyze wellness attributes] for more details.

=== Smarter and faster search
Allows you to search parameters, such as serial number, system ID, host name, site name, group name, and cluster name using the single-system view. You can also search for group of systems, in addition, you can search by a customer name, site name, or group name by group of systems.
