---
sidebar: sidebar
permalink: reference_new_activeiq.html
keywords: what's new, features, new
summary: Provides information about the new features in the release.
---

= What's new in Active IQ Digital Advisor
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Active IQ typically introduces a new release every month to bring you the new features and enhancements.

== 19 June 2020
This update includes the following new features, enhancements, and changes:

=== Generate report for inventory
You can now generate report of the selected watchlist and emails the report to a maximum of 5 recipients.

=== Performance
Performance graphs have been enhanced to enable you to assess the cluster performance of your storage system.

=== Update the default home page
You can now provide your feedback and let us know the reason you are the updating the default home page screen for Active IQ.

== 19 May 2020
This update includes the following new features, enhancements, and changes:

=== Set the default home page
You can now set the default home page screen for Active IQ. You can either set it to Active IQ Digital Advisor or Active IQ Classic.

=== Storage efficiency
You can view the storage efficiency ratio and savings of your storage system with and without Snapshot backups for AFF systems, non-AFF systems, or both. You can view the storage efficiency information at a cluster level or a node level.

=== Performance
Performance graphs enable you to assess the performance of your storage devices in different significant areas.

=== Support offerings
Lists the features that are supported based on the following support offerings:

** SupportEdge Warranty
** SupportEdge Basic
** SupportEdge Standard
** SupportEdge Premium
** SupportEdge Advisor
** SupportEdge Expert

=== AFF/FAS firmware upgrades using Ansible
Update the AFF/FAS firmware using Ansible on your storage system to mitigate the identified risks and to keep your storage system up to date.

=== Disabling the wellness score feature
The wellness score feature is being temporarily disabled to improve the scoring algorithm and simplify the overall experience.

== 02 April 2020
This update includes the following new features and enhancements:

=== Onboarding overview video
The onboarding video helps users to quickly get familiar with the options and features of Active IQ Digital Advisor.

=== Wellness score
Wellness score provides customers with a consolidated score of their installed base based on the number of high risks and the expired contracts. Score can be good, average, or poor.

=== Risk summary
The risk summary provides detailed information about the risk, the impact of the risk, the corrective actions.

=== Support for acknowledging and disregarding risks
Provides the option to acknowledge a risk if you do want to mitigate or are unable to mitigate the risk.

== 19 March 2020
This update includes the following new features and enhancements:

=== Upgrade workflow
You can use the upgrade workflow to view upgrade recommendations and a summary of new features available in your target ONTAP release.

=== Valuable insights
You can view the summary of the benefits that you received through Active IQ and your support contract. For selected systems, the value report consolidates the  benefits from last one year.

=== Drill into details
Provides deeper information, which is a powerful way to dig deeper into the data and gain immediate insights into the make-up of aggregated information as required.

=== Capacity additions
You can proactively identify systems that have exceeded capacity or are nearing 90% capacity and send a request to increase capacity.

== 29 February 2020
This update includes the following new features and enhancements:

=== Enhanced user interfaces
The latest Active IQ Digital Advisor Dashboards offer a personalized experience. It allows smooth and seamless navigation, with its intuitiveness, throughout different dashboards, widgets, and screens. It provides an	all-in-one experience. It communicates comparisons, relationships, and trends. It provides insights that help you detect and validate important relationships and meaningful differences based on the data that is presented by different dashboards.

=== Customizable dashboards
Helps you monitor your systems at a glance by providing key insights and analysis about your data on one or more pages or screens. You can also create up to 10 dashboards and make effective business decisions.

=== Mitigate risks using Active IQ Unified Manager
You can view the risks and rectify them by using Active IQ Unified Manager.

=== Wellness
Provides detailed information about the status of your storage system that is classified into the following 6 widgets:
[disc]
* Performance & Efficiency
* Availability & Protection
* Capacity
* Configuration
* Security
* Renewals

=== Smarter and faster search
Allows you to search parameters, such as serial number, system ID, host name, site name, group name, and cluster name using the single-system view. You can also search for group of systems, in addition, you can search by a customer name, site name, or group name by group of systems.
