---
sidebar: sidebar
permalink: reference_aiq_faq.html
keywords: faq, frequently asked questions, nontechnical, nontechnical case, non-technical, non-technical case
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions about Active IQ
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The following questions give answers to your frequent queries about Active IQ.

== Nontechnical case

*What is a nontechnical case?*

Issues such as unable to view systems in the inventory, incorrect contract term dates, and so on, which are not technical in nature are classified as nontechnical cases.

*When do I need to create a nontechnical case?*

A nontechnical case should be created for the following cases:

* Unable to access certain features
* Missing systems in inventory
* Decommissioning a system from the install base
* Incorrect or missing contract term dates
* Incorrect support offering

*How do I create a nontechnical case?*

. Click link:https://mysupport.netapp.com/site/help[here] to open the “Non Technical Feedback Tool" on the NetApp Support site.
. Select the appropriate category from the *Feedback Category* drop-down list.
. Enter the required details and provide additional information in the “Comments” box”.
. Click *Submit*.

A case is created, and a case number is provided for your reference.

*How do I provide feedback or ask other questions related to Active IQ?*

To provide feedback or ask questions, send an email to mailto:ng-activeiq-feedback@netapp.com[[.underline]#ng-activeiq-feedback@netapp.com#].

== Storage efficiency

*How do I access Storage Efficiency in Active IQ Digital Advisor?*

. Open the home page of link:https://activeiq.netapp.com/?source=onlinedocs[Active IQ Digital Advisor].
. Search for a customer, site, group, cluster, or node from the top right search box to reach the respective dashboard.
. Click *Storage Efficiency* from the left navigation.

NOTE: The dashboards created using a watchlist will not be displayed in the Storage Efficiency widget.

*Does Active IQ Digital Advisor display ratios for all ONTAP systems?*

Active IQ displays ratios for systems running ONTAP 9.1 and later.

*What is the ‘Without Snapshots’ checkbox on the efficiency dashboard?*

By default, Active IQ Efficiency Dashboard calculates overall ratio at customer-level, site-level, group-level, cluster-level, and node-level. Overall ratio includes the ratio from the following storage efficiency technologies:

	* Deduplication
	* Compression
	* Data compaction
	* Clones
	* Snapshots

If you select the *Without Snapshots* checkbox, Active IQ Digital Advisor will calculate efficiency ratio (ratio from deduplication, compression, data compaction and clones storage efficiency technologies) at customer-level, site-level, group-level, cluster-level and node-level.

*What is physical data used and logical data used?*

* Physical Blocks Consumed / Physical Data Used
** The amount of space being used for data now (rather than being reserved for future use)
** Includes space used by aggregate Snapshot copies
** Space actually consumed/written by the client

* Total Logical Data Used
** Displays the logical size used in the aggregate.
** This includes Volumes, Clones, and Snapshots in the aggregate.
** The logical size is computed based on physical usage (real writes) and savings obtained in the aggregate.
** Does not include space reserved for future use

*Which AutoSupport instances are used for calculating efficiency ratios?*

Calculations are performed using either the latest weekly or user-triggered AutoSupport instances which tend to contain most of the sections required for calculating the ratios.

*Which volumes or aggregates are excluded from efficiency calculations?*

The following objects are not considered while calculating efficiency ratios:

* Root aggregates
* Offline volumes
* Vserver root/admin root volumes
* MCC configuration volumes

*How can I see the trend in efficiency ratios?*

Currently, efficiency ratios are calculated based on the latest weekly or user-triggered AutoSupport instance. Efficiency trending may be considered for a future release.

*How are customer-level ratios and efficiency savings calculated?*

Customer-level storage efficiency dashboard provides the efficiency ratio with and without Snapshot copies for AFF and non-AFF systems and are combined across the customer installed base for systems running ONTAP 9.1 and later. The required parameters for the following calculations are taken from ONTAP AutoSupport:

Without Snapshot copies (calculated for per Aggr first):

[%autowidth, indent=8]
|===
    |*Operation*  | *Formula*

    |Aggr Logical Used without Snapshot copies | Logical Size Used by Volumes, Clones, Snapshot Copies in the Aggregate – Logical Size Used by Snapshot Copies
    |Aggr Physical Used Without Snapshot copies | Total Physical Used – (Physical Size Used by Snapshot copies / Aggregate Data Reduction SE Ratio)
    |Customer Efficiency Ratio without Snapshot copies | Sum [Aggr Logical Used without Snapshot copies for all aggregates and for all nodes of a customer] / Sum [Aggr Physical Used without Snapshot copies for all aggregates and for all nodes of a customer] : 1
|===

With Snapshot copies:

[%autowidth, indent=8]
|===
    |*Operation*  | *Formula*

    |Customer Logical Size with Snapshot copies | Sum [Logical Size Used by Volumes, Clones, Snapshot copies for all aggregates and for all nodes of a customer]
    |Customer Physical Size Used with Snapshot copies | Sum [Total Physical Size Used for all aggregates and for all nodes of a customer]
    |Customer Efficiency Ratio with Snapshot copies | Customer Logical Size with Snapshot copies and Clones / Customer Physical Size Used with Snapshot copies and Clones : 1
|===

Efficiency feature table calculations:

[%autowidth, indent=8]
|===
    |*Operation*  | *Formula*

    |Customer Physical Space Used | Sum of Physical Space Used by the Aggregate for all aggregates and of all nodes of a customer
    |Customer Logical Size Used without Snapshot copies | Sum of Logical Size Used by Volumes, Clones, Snapshot Copies - Logical Size Used by Snapshot copies for all aggregates of all nodes of a customer
    |Customer Logical Size Used with Snapshot copies | Sum of Logical Size Used by Volumes, Clones, Snapshot Copies in the Aggregate for all aggregates of all nodes of a customer
		|Total Space Saved | Total Logical Space Used – Total Physical Space Used
    |Deduplication Savings | Sum of Space Saved by Volume Deduplication + Space Saved by Inline Zero Pattern Detection of each aggregate of all nodes of a customer
		|Compression Savings | Sum of Space Saved by Volume Compression of each aggregate of all nodes of a customer
		|Compaction Savings (for ONTAP 	9.1) | Sum of Space Saved by Aggregate Compaction of each aggregate of all nodes of a customer
    |Compaction Savings (for ONTAP 	9.2 and later) | Sum of Space Saved by Aggregate Data Reduction of each aggregate of all nodes of a customer
		|FlexClone Savings | Sum of (Logical Size Used by FlexClone Volumes - Physical Sized Used by FlexClone Volumes) of each aggregate of all nodes of a customer
    |Snapshot copies Backup Savings | Sum of (Logical Size Used by Snapshot copies - Physical Size Used by Snapshot copies) of all aggregates of all nodes of a customer
|===

*Why does adding all individual efficiency savings not add up to total data saved by storage efficiency?*

Efficiency savings are shown in the Storage Efficiency Dashboard for volumes and local tiers (aggregates).  You cannot add volume savings and aggregate savings as they both happen at different storage objects.

*Why were storage efficiencies reported as higher or incorrectly before upgrading to ONTAP?*

Storage efficiency is shown higher when data protection volumes are present in the node due to a bug in ONTAP. The issue was fixed in ONTAP 9.3P11. Storage Efficiency reports correct or lower values when upgraded from ONTAP versions earlier than 9.3P11 and when data protection volumes are present in the node.

== Capacity

*How are capacities calculated in Active IQ Digital Advisor?*
The capacities in Active IQ Digital Advisor are calculated for cluster and node — excluding root and including Snapshot copies
[%autowidth, indent=10]
|===
    |*Capacity*  | *Calculated by adding each aggregate…*

    |Raw Capacity | All Phys (MB/blks) of “SYSCONFIG -R"
    |Usable Capacity | Kbytes (Allocated) of "DF -A"
    |Used Capacity (with Reserve) | Used of   “DF -A”
    |Available Capacity | Avail of “DF -A”
    |Physical Capacity (Actual)| Total Physical Used of “AGGR-EFFICIENCY.XML”
    |Logical Capacity (Effective)| Logical Size Used by Volumes, Clones, and Snapshot copies in the Aggregate of “AGGR-EFFICIENCY.XML”
|===

*For Local tier (Aggregate with Snapshot copies)*
[%autowidth, indent=10]
|===
    |*Capacity*  | *Calculated by using…*

    |Usable Capacity | Kbytes (allocated) of "DF -A"
    |Used Capacity (with Reserve) | Used of   “DF -A”
    |Available Capacity| Avail of “DF -A”
    |Physical Capacity (Actual)| Total Physical Used of “AGGR-EFFICIENCY.XML”
    |Logical Capacity (Effective)| Logical Size Used by Volumes, Clones, and Snapshot copies in the Aggregate of “AGGR-EFFICIENCY.XML”
|===

*For Volume (Volume with Snapshot copies)*
[%autowidth, indent=10]
|===

    |*Capacity*  | *Calculated by using…*

    |Volume Capacity | Volume Size of “VOLUME.XML”
    |Used Capacity (with Reserve) | Used Size of "VOLUME.XML"
    |Available Capacity| Available Size of “VOLUME.XML”
    |Physical Capacity (Actual)| Total Physical Used of “VOL STATUS -S”
    |Logical Capacity (Effective)| Logical Used Size of “VOLUME.XML”
|===

*What are Physical Capacity (Actual), Logical Capacity (Effective), and Used Capacity (with Reserve)?*

* Physical Blocks Consumed/Physical Capacity Used (Actual)
** The amount of space being used for data now (rather than being reserved for future use)
** Includes space used by aggregate Snapshot copies
** Space actually consumed or written by the client

* Logical Capacity (Effective) Logical Data Used
** Displays the logical size used in the aggregate
** The aggregate incudes Volumes, Clones, and Snapshot copies.
** The logical size is computed based on physical usage (real writes) and savings obtained in the aggregate.

NOTE:	It does not include space reserved for future use.

* Total Data Used/Used Capacity (with Reserve)
** The sum of all space used or reserved in the aggregate by volumes, metadata, or Snapshot copies

NOTE: It includes space reserved for volumes that are of file or volume guarantee type. It includes delayed frees, aggr blog, and metadata in addition to reserves. It shows up as used space until the delayed free blocks are purged. After it is purged, the used space decreases.

*How is the Capacity Forecast calculated?*
The Capacity Forecast uses used capacity data over the last year to calculate the average weekly growth rate of a system. This rate of change in system usage is then extrapolated forward from the current used capacity, to demonstrate how system utilization is expected to change over the next 6 months (assuming  the total usable capacity remains the same).

*Why does added Used Capacity of each volume not match the aggregated Used Capacity at the node level?*
Used Capacity at the node level includes space reserved by volumes, metadata, and Snapshot copies. It also includes space reserved for volumes—file or volume guarantee type. Hence, both might not match.

*Are Capacities shown in Active IQ Digital Advisor Base 2 or Base 10?*
All capacities displayed in Active IQ are Base 2 (divide by 1024) and represent capacities in GiB/TiB. ONTAP storage and other NetApp products also display capacity usage in Base 2.

For StorageGRID, capacities are displayed in Base 10 and the unit of capacity is expressed in TB.

== Inventory

*Why cannot I find my systems in the inventory page?*
You will not be able to view the systems in the inventory page due to one of following scenarios:
* New systems take over a day to reflect in Active IQ
* The user does not have a secure profile
* The user does not have entitlements
* Systems are inactive

In such cases, you should create a nontechnical case. <<Nontechnical case,Learn more about creating a nontechncial case.>>
