---
sidebar: sidebar
permalink: task-integrating-with-cloud-insights-to-view-vm-details.html
keywords: Cloud Insights, VMs, virtual machines, Data Infrastructure Insights
summary: Provides information about the virtual machines in Data Infrastructure Insights
---

= Use Digital Advisor to view virtual machines data available in Data Infrastructure Insights
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Digital Advisor is now integrated with Data Infrastructure Insights Basic version to provide a full stack inventory and interoperability checks to customers.

The benefits of this integration are:

* Simplified SaaS monitoring of ONTAP
* Visibility into VMware full-stack monitoring
* Productivity savings for customers through automated interoperability checks to help with ONTAP upgrade planning. This results in smoother ONTAP upgrades and reduces risks of incompatibility with hosts.

NOTE: This feature is available only for SupportEdge Advisor, SupportEdge Expert, and Digital Advisor Upgrade contracts.

.Steps
. In the *Inventory* widget, click *Virtual Machines* to view the data available in Data Infrastructure Insights.
. Click the *Virtual Machine Overview* tab.
. Click the *Count of ESX Hosts* to view information about the host.
. Click the *ESX Name* to navigate to Data Infrastructure Insights to view more information.
