---
sidebar: sidebar
permalink: task_install_execute_firmware_update_exp_user.html
keywords: install, execute, firmware update, ansible playbook, ansible, playbook, docker, experienced user
summary: Provides information to install and execute firmware update using ansible playbook.
---

= Install and execute FAS/AFF firmware Ansible automation package (Experienced Users)
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Experienced users can follow the steps below to install and execute the FAS/AFF firmware ansible automation package quickly.

Users who require detailed steps to install and execute the FAS/AFF firmware ansible automation package, click here.

== Firmware update with Ansible using NetApp Docker Image

.Steps
. Pull the Ansible Docker image to the Linux host
+
----
$ docker pull schmots1/netapp-ansible
Using default tag: latest
latest: Pulling from schmots1/netapp-ansible
docker.io/schmots1/netapp-ansible:latest
----
. Run the docker image as container on the Linux host
+
----
Playbook and the inventory file must be in the same path.
$ docker run -v <downloaded_playbook_path>:/<container_path> -it schmots1/netapp-ansible:latest /bin/bash
----
. Execute the playbook on the Linux host. Firmware updates will occur as a background process over a few hours.
+
----
$ cd <container_path>
$ ansible-playbook na_ontap_pb_upgrade_firmware.yml

Enter your ONTAP admin username: ****
Enter the password for your ONTAP admin user: ****
Enter the base URL to the firmware package (using HTTP is recommended): http://<web-server>/path/
PLAY [ONTAP Firmware Upgrade] ****************************************************************
----
NOTE: If the URLs for disk firmware and shelf firmware are _http://<web-server>/path/all_shelf_fw.zip_ and _http://<web-server>/path/all.zip_, provide _http://<web-server>/path/_  as the input for the base URL to the firmware package.

. Log in to the cluster as the cluster administrator and verify that the new drive firmware has been installed
+
----
::> storage disk show -fields firmware-revision,model
 disk     firmware-revision model
--------------- ----------------- ----------------
1.11.0   NA01              X423_HCOBE900A10
1.11.1   NA01              X423_HCOBE900A10
1.11.2   NA01              X423_HCOBE900A10
1.11.3   NA01              X423_HCOBE900A10
1.11.4   NA01              X423_HCOBE900A10
----


== Firmware update if Ansible is already used

.Steps
. Install Python and Ansible and then download the Python packages using PIP:
+
----
$ pip install netapp-lib requests

Installing collected packages: netapp-lib, requests
Successfully installed netapp-lib-2020.3.12 requests-2.23.0
----
. Install the NetApp Ansible Collection
+
----
To install the collection only for the current user:
$ ansible-galaxy collection install netapp.ontap

For universal installation:
$ ansible-galaxy collection install netapp.ontap -p /usr/share/ansible/collections
$ chmod -R +rw /usr/share/ansible/collections
----
. Execute the playbook. Firmware updates run in the background for a few hours
+
NOTE: The playbook and the inventory file must be in the same path.

----
$ cd <playbook_path>
$ ansible-playbook na_ontap_pb_upgrade_firmware_disk.yml

Enter your ONTAP admin username: ****
Enter the password for your ONTAP admin user: ****
Enter the base URL to the firmware package (using HTTP is recommended): http://<web-server>/path/
PLAY [ONTAP Firmware Upgrade] ****************************************************************
----
. Log in to the cluster as the cluster administrator and verify that the new drive firmware has been installed.
+
----
::> storage disk show -fields firmware-revision,model
 disk     firmware-revision model
--------------- ----------------- ----------------
1.11.0   NA01              X423_HCOBE900A10
1.11.1   NA01              X423_HCOBE900A10
1.11.2   NA01              X423_HCOBE900A10
1.11.3   NA01              X423_HCOBE900A10
1.11.4   NA01              X423_HCOBE900A10
----
