---
sidebar: sidebar
permalink: task_view_cluster_and_node_configuration.html
keywords: cluster, node, configuration
summary: Provides information about the cluster and node configurations.
---

= View cluster and node configuration
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The ClusterViewer enables you to view detailed physical and logical configuration information. The details are presented in several easy-to-view tables across multiple tabs that include a summary of the cluster and node configuration, the local tier and volume information, the network interface and port information, a stack diagram detailing information about the disks and shelves, and a few cable visualizations. You can also download the cable visualization graphics in the SVG format.

video::FVbb2bbIY9E[youtube, width=848, height=480]

.Steps
. At the cluster level, click *View Details* next to the *Cluster Configuration* widget.
. Click the *Visualization* tab to view a graphical representation of the cluster.
