---
sidebar: sidebar
permalink: task_login_activeiq.html
keywords: login, log in
summary: Provides information to log in to Digital Advisor.
---

= Log in to Digital Advisor
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can log in to Digital Advisor from a web-based console for viewing the overall status of your storage system.

.Before you begin
You must have a valid NetApp Support site credential to log in to Digital Advisor. If you do not have an account and are getting started, see the following KB article to create an account:
link:https://kb.netapp.com/Support/General_Support/How_to_register_for_a_NetApp_Support_Site_account_as_a_Customer_or_a_Guest_user[How to register for NetApp Support Site account as a Customer or a Guest user^].

.Steps
. Go to the link:https://activeiq.netapp.com/?source=onlinedocs[Digital Advisor^] login page.
+
Digital Advisor shows systems with a valid support contract. If contracts expire, a grace period of 90 days is given in which systems continue to be visible. Thereafter, systems are not searchable or visible within Digital Advisor.
. Provide your username and password and click *Sign In*.
