---
sidebar: sidebar
permalink: task_analyze_storage_efficiency.html
keywords: renew, hardware, software
summary: Provides information to renew the software and hardware of your storage system.
---

= Analyze storage efficiency savings
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The storage efficiency dashboard displays the storage efficiency ratio, the logical space used, the physical space used, and the total data saved for storage systems running ONTAP 9.1 and later. The efficiency ratio and savings can be seen with and without Snapshot backups for AFF systems, non-AFF systems, or both. You can view the storage efficiency information either at a cluster level or a node level.

The total savings across customer storage can be seen per efficiency feature such as volume deduplication, volume compression, compaction, FlexClone volumes, and Snapshot backups. You can also view the top 5 storage systems with the best efficiency ratio.

video::8Ge3_0qlyxA[youtube, width=848, height=480]

.Steps
. From the left pane, click *Storage Efficiency*.
. View the storage efficiency and the data savings of your storage system.
+
Based on the condition of your storage system, you can either share your success story or contact NetApp to help improve the storage efficiency of your system.
. If the storage efficiency ratio of your storage system is higher than the average storage efficiency ratio, click *Share Your Success Story* to let us know the best practices followed.
. If the storage efficiency ratio of your storage system is less than the average storage efficiency ratio, click *Contact Us* to let us know the configurations of your storage system.
