---
sidebar: sidebar
permalink: task_view_performance_graphs.html
keywords: performance, performance graph, graphs, activeiq, active iq digital advisor, performance charts, day, week, 1 month, 2 months, calendar, chart data, performance on node level, graph, node level
summary: Provides information about the performance.
---

= Analyze performance graphs
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can view the performance of the cluster, node, and local tier and take appropriate actions to make optimum use of your storage system.

.Steps
. On the Dashboard, click *Performance*.
+
By default, the cluster performance is displayed. You can click the *Node* tab to view the performance of a single node of an ONTAP cluster or click the *Local Tier* tab to view the performance of the local tier.
. Select either 1 day, 1 week, 1 month, or 2 months, in the calendar, for viewing performance data in a graphical format. Confirm that you want to perform the operation.
+
For example, select 2-months tab to view data for 2 months. This enables you to view specific data for a duration based on your performance requirements.
. View performance graphs with required metrics, including:

[cols=3*,options="header",cols="25,35,40"]
|===
| For Cluster
| For Node
| For Local Tier
| IOPS | CPU Utilization - Peak Performance (Headroom) | Local Tier Utilization
| Network Throughput | Latency  |
|   | IOPS |
|   | Protocol IOPS |
|   | Network Throughput |
|===

NOTE: Node latency performance graphs are supported only on systems that are running ONTAP 9.2 and later.
