---
sidebar: sidebar
permalink: task_generate_reports.html
keywords: reports, generate reports
summary: Provides information to generate reports.
---

= Generate or schedule a report in Digital Advisor
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can generate reports immediately or schedule a report to be generated on a weekly or monthly basis. The reports can be generated in different formats. Based on the report selected, the available formats are displayed.

*About this task*

* You cannot edit the reports in Digital Advisor. You should delete the existing report and create a new report.

.Steps
. From the left pane, click *Reports*.
. Click *Create Report* to generate a new report.
+
You can generate a report immediately or you can schedule the report to be generated on a weekly or monthly basis.

[cols=2*,options="header", cols="50,50"]
|===
| To generate a report immediately
| To schedule the report to be generated on a weekly or monthly basis
a|
. Select the type of report and provide the requested values for the report.
. Select the format of the report.
. Click *Submit*.

NOTE: The report is saved in Digital Advisor for 3 months.

a|
. Click the *Schedule Report* tab.
. Select the type of report and provide the requested values for the report.
. Select the format of the report.
. Select the frequency of the report.
. Select the start date and end date for the report.
. Click *Submit*.

NOTE: The existing scheduled reports will be replaced when the new reports are generated.

|===
