---
sidebar: sidebar
permalink: task_subscribe_to_wellness_review_email.html
keywords: wellness, wellness review subscription, unsubscribe, supportedge expert, supportedge advisor
summary:
---

= Subscribe to storage system health notifications from Digital Advisor
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can subscribe to the wellness review email to receive a monthly email that summarizes wellness status, systems that are nearing their renewal dates, systems that require an upgrade for the NetApp products in your installed base.
You will receive a wellness review email so that you can view a monthly summary and take action for your systems.
You also have options to view, edit, share, and delete your subscriptions. At any time, if you decide to not receive the email, you can unsubscribe from getting email as well.

After the subscription is enabled, you should select a start date when adding a subscription.
The monthly email summary provides a view of outstanding wellness, renewal, upgrade, and health check actions. You can confirm the email address and the email is sent to the specified email address.
You also have the option to delete subscriptions.

NOTE: This feature is available only through NetApp SupportEdge Advisor and SupportEdge Expert service offerings.

.Steps
. From the left pane, click *Wellness Review*.
. Click *Add Subscription*.
. Provide the required information in the *Name the Subscription*, *Choose Category*, *Search Customer*, and *Email* fields in the *Add New Subscription* dialog box.
. Click *Subscribe*.
+
Upon successful subscription, you will receive a *Subscription was added* message.
