---
sidebar: sidebar
permalink: task_subscribe_to_wellness_review_email.html
keywords: wellness, wellness review subscription, 1 month, monthly, email, activeiq, active iq digital advisor,
summary:
---

= Subscribe to wellness review email
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can subscribe to the wellness review email to receive a monthly email that summarizes wellness status, systems that are nearing renewal, systems that require an upgrade for the NetApp products in your installed base.
You will receive a wellness review email so that you can view a monthly summary and take action for your systems.

After the subscription is enabled, the email is sent monthly on the first Monday of each month.
The monthly email summary provides a view of outstanding wellness, renewal, upgrade, and health check actions. You can confirm the email address and the email is sent to the specified email address.

.Steps
. On the Dashboard, click *Wellness Review Subscription*.
. Click *Wellness Review Subscription*.
. Click *Add Subscription*.
. Provide the required information in the *Name the Subscription*, *Choose Category*, *Search Customer*, and *Email* fields in the *Add New Subscription* dialog box.



. Click *Subscribe*.
Upon successful subscription, a *Subscription was added* message is sent.
