---
sidebar: sidebar
permalink: task_validate_firmware_installation.html
keywords: validate, firmware, firmware installation
summary: Provides information to validate the firmware installation.
---

= Validate firmware installation
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After the execution of the playbook, log in to the cluster as the cluster administrator.

== Validate disk firmware installation

.Steps
. Verify that the drive firmware is installed:
+
----
::*> storage disk show -fields firmware-revision,model
disk     firmware-revision model
--------------- ----------------- ----------------
1.11.0   NA01              X423_HCOBE900A10
1.11.1   NA01              X423_HCOBE900A10
1.11.2   NA01              X423_HCOBE900A10
1.11.3   NA01              X423_HCOBE900A10
1.11.4   NA01              X423_HCOBE900A10
----
:link-with-underscores: https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.dot-cm-cmpr-910%2Fstorage__disk__show.html
For more information about the command, refer to {link-with-underscores}[storage disk show].

. Verify that new NVMe Flash Cache firmware is installed:
+
----
::*> system controller flash-cache show
----
:link-with-underscores: https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.dot-cm-cmpr-960%2Fsystem__controller__flash-cache__show.html
For more information about the command, refer to {link-with-underscores}[system controller flash-cache show].

== Validate shelf firmware installation

.Steps
. Verify that the new shelf firmware is updated:
+
----
::*> system node run -node * -command sysconfig -v
----
In the output, verify that each shelf's firmware is updated to the desired level. For example:
+
----
Shelf 1: IOM6 Firmware rev. IOM6 A: 0191 IOM3 B: 0191
----
:link-with-underscores: https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-970/system__node__run.html
For more information about the command, refer to {link-with-underscores}[system node run].

. Verify that the new ACP firmware is updated:
+
----
::*> storage shelf acp module show -instance
----
:link-with-underscores: http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-970/storage__shelf__acp__module__show.html
For more information about the command, refer to {link-with-underscores}[storage shelf acp module show].

. Verify that the desired ACP mode is configured:
+
----
::*> storage shelf acp show
----
:link-with-underscores: https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-910/storage__shelf__acp__show.html
For more information about the command, refer to {link-with-underscores}[storage shelf acp show].

. Change the ACP mode (channel):
+
----
::*> storage shelf acp configure -channel [in-band | out-of-band]
----
:link-with-underscores: http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-970/storage__shelf__acp__configure.html
For more information about the command, refer to {link-with-underscores}[storage shelf acp configure].

== Validating SP/BMC Firmware installation

The Ansible Playbook for Service Processor/BMC firmware updates is enabled with an option to verify the installation of latest SP/BMC Firmware on the controller. After the verification is complete (the updates could take a maximum time of two hours), the Ansible Playbook applies internal switch firmware updates by connecting to the SP/BMC console.

The failure and success information for SP/BMC Firmware and the internal switch firmware installations will be notified at the end of Ansible Playbook execution. Follow the steps mentioned in the Ansible Playbook in case the SP/BMC Firmware/internal switch Firmware installation fails.
