---
sidebar: sidebar
permalink: task_add_watchlist.html
keywords: dashboard, watchlist, add watchlist
summary: Provides information to add a watchlist to the dashboard.
---

= Create a watchlist
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can create a watchlist to access a set of systems quickly and easily. You can add the systems based on category or serial number.

.Steps
. From the left pane, click *Watchlists*
+
The *Manage Watchlist* screen is displayed.
. Click *Create Watchlist*.
. Provide a name for the watchlist.
. Select one of the following options to add systems to the watchlist:

  * *Category*: This option enables you to add the entire inventory associated with a specific category, such as customer, site, group, or Keystone subscriptions, to your watchlist.
  +
NOTE: The *Keystone Subscriptions* option allows you to include any subscription numbers associated with Keystone subscriptions. On searching by a watchlist, you can view the subscriptions in the *Keystone Subscriptions* widget on the Digital Advisor dashboard. For more information, see link:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-aiq.html#search-by-keystone-watchlists[Search by Keystone watchlists^].

  * *Serial Number*: This option enables you to include inventory in your watchlist based on specified serial numbers. You can either input the serial number directly or select serial numbers from categories like customer, site, or group.
+
 
NOTE: You can add a maximum of 15,000 systems under a category and 500 systems under a serial number.

. Click *Create Watchlist*.
+
The watchlist dashboard is displayed.
