---
sidebar: sidebar
permalink: task_identify_capacity_system.html
keywords: capacity, space, increase, ONTAP systems, StorageGRID
summary: Provides information to increase the capacity of the system.
---

= Identify systems reaching capacity limits
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Proactively identify systems reaching capacity limits and send a request to increase the capacity of your storage system.

For ONTAP, you can view systems that have exceeded 90% capacity or are to exceed 90% capacity in 1, 3, and 6 months. For StorageGRID, you can view systems that have exceeded 70% capacity or are to exceed 70% capacity in 1, 3, and 6 months. 

.Steps
. In the *Planning* widget, click *Capacity Additions*.
+
By default, the ONTAP systems that have exceeded 90% capacity or are nearing 90% capacity are displayed.
. Click *StorageGRID* tab to view the StorageGRID systems that have exceeded 70% capacity or are nearing 70% capacity.
. Select the systems for which you want to increase capacity  and click *Request to Add Capacity*.
. Optionally, provide any comments.
. Click *Send* to send the request to increase capacity.
