---
sidebar: sidebar
permalink: task_add_watchlist.html
keywords: dashboard, watchlist, add watchlist
summary: Provides information to add a watchlist to the dashboard.
---

= Create a watchlist
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can create a watchlist to access a set of systems quickly and easily. You can add the systems based on category or serial number.

.Steps
. From the left pane, click *Watchlists*
+
The *Manage Watchlist* screen is displayed.
. Click *Create Watchlist*.
. Provide a name for the watchlist.
. Select one of the following options to add systems to the watchlist:

  * *Category*: This option allows you to include systems based on customer, site, or group category. For example, you can select different sites with the Site category, and this will include all the systems associated with these sites in a single watchlist.
  * *Serial Number*: This option allows you to include specific systems based on customer, site, or group category. For example, you can select specific systems from different groups with the Group category to create a single watchlist.
+
 
NOTE: You can add a maximum of 15,000 systems under a category and 500 systems under a serial number.

. Click *Create Watchlist*.
+
The watchlist dashboard is displayed.
