---
sidebar: sidebar
permalink: task_install_execute_firmware_update_exp_user.html
keywords: install, execute, firmware update, Ansible Playbook, ansible, playbook, docker, experienced user
summary: Provides information to install and execute firmware update using Ansible Playbook.
---

= Install and execute AFF and FAS firmware Ansible automation package (Experienced Users)
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Experienced users can follow the steps below to install and execute the AFF and FAS firmware ansible automation package quickly.

== Firmware update with Ansible using NetApp Docker Image

.Steps
. Pull the Ansible Docker image to the Linux host:
+
----
$ docker pull schmots1/netapp-ansible
Using default tag: latest
latest: Pulling from schmots1/netapp-ansible
docker.io/schmots1/netapp-ansible:latest
----
. Run the docker image as container on the Linux host:
+
----
$ docker run -v <downloaded_playbook_path>:/<container_path> -it schmots1/netapp-ansible:latest /bin/bash
----
NOTE: The Ansible Playbook and the inventory file should be in the same path.

. Execute the Ansible Playbook on the Linux host. Firmware updates run in the background for a few hours.
+
----
$ cd <container_path>
$ ansible-playbook na_ontap_pb_upgrade_firmware.yml

Enter your ONTAP admin username: ****
Enter the password for your ONTAP admin user: ****
Enter the base URL to the firmware package (using HTTP is recommended): http://<web-server>/path/
PLAY [ONTAP Firmware Upgrade] ****************************************************************
----
NOTE: If the URLs for disk firmware, shelf firmware, and service processor firmware are *\http://<web-server>/path/all_shelf_fw.zip*, *\http://<web-server>/path/all.zip* and  *\http://<web-server>/path/<SP/BMC>_<version_number>_fw.zip*, provide *\http://<web-server>/path/* as the input for the base URL to the firmware package. If there are set of clusters with different login credentials, the Ansible Playbook must be run on each cluster. There are no changes required to the inventory file as the Ansible Playbook skips the clusters for which the login has failed.

. Log in to the cluster as the cluster administrator and verify that the new drive firmware has been installed:
+
----
::> storage disk show -fields firmware-revision,model
 disk     firmware-revision model
--------------- ----------------- ----------------
1.11.0   NA01              X423_HCOBE900A10
1.11.1   NA01              X423_HCOBE900A10
1.11.2   NA01              X423_HCOBE900A10
1.11.3   NA01              X423_HCOBE900A10
1.11.4   NA01              X423_HCOBE900A10
----


== Firmware update if Ansible is already used

.Steps
. Install Python and Ansible and then download the Python packages using PIP:
+
----
$ pip install netapp-lib requests paramiko

Installing collected packages: netapp-lib, requests, paramiko
Successfully installed netapp-lib-2020.3.12 requests-2.23.0 paramiko-2.7.2
----
. Install the NetApp Ansible Collection:
+
----
To install the collection only for the current user:
$ ansible-galaxy collection install netapp.ontap

For universal installation:
$ ansible-galaxy collection install netapp.ontap -p /usr/share/ansible/collections
$ chmod -R +rw /usr/share/ansible/collections
----
. Ensure that the Ansible Playbook and the inventory file are in the same path and then execute the Ansible Playbook. Firmware updates run in the background for a few hours.
+
----
$ cd <playbook_path>
$ ansible-playbook na_ontap_pb_upgrade_firmware_disk.yml

Enter your ONTAP admin username: ****
Enter the password for your ONTAP admin user: ****
Enter the base URL to the firmware package (using HTTP is recommended): http://<web-server>/path/
PLAY [ONTAP Firmware Upgrade] ****************************************************************
----
NOTE: If the URLs for disk firmware, shelf firmware, and service processor firmware are *\http://<web-server>/path/all_shelf_fw.zip*, *\http://<web-server>/path/all.zip* and  *\http://<web-server>/path/<SP/BMC>_<version_number>_fw.zip*, provide *\http://<web-server>/path/* as the input for the base URL to the firmware package. If there are set of clusters with different login credentials, the Ansible Playbook must be run on each cluster. There are no changes required to the inventory file as the Ansible Playbook skips the clusters for which the login has failed.

. Log in to the cluster as the cluster administrator and verify that the new drive firmware has been installed:
+
----
::> storage disk show -fields firmware-revision,model
 disk     firmware-revision model
--------------- ----------------- ----------------
1.11.0   NA01              X423_HCOBE900A10
1.11.1   NA01              X423_HCOBE900A10
1.11.2   NA01              X423_HCOBE900A10
1.11.3   NA01              X423_HCOBE900A10
1.11.4   NA01              X423_HCOBE900A10
----
