---
sidebar: sidebar
permalink: task_view_upgrade.html
keywords: upgrade, ONTAP version, upgrade advisor, upgrade plan, risk advisor, pending upgrades
summary: Provides information to view and upgrade the ONTAP version of your storage system.
---

= Upgrade the ONTAP version by generating an upgrade plan
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can view the pending upgrades of your storage system and upgrade to a later version of ONTAP by generating an upgrade plan. You should also view the list of risks in the *Risk Advisor* tab which would be mitigate because of the upgrade.

// 2021-06-02, Jira AIQ-49239, Reenu
// You can also view the current interoperability data. It is populated based on Active IQ OneCollect AutoSupport data.

.Steps
. On the dashboard, view pending upgrades in the *Upgrades* widget.
. Click the number of *Actions* to view the pending upgrades.
. Select the required upgrade option.
. Click the number of systems displayed on the widget to view the *Upgrade Advisor* tab.
+
You can also check the Release Notes to view detailed information about the release.
. View the list of risks in the *Risk Advisor* tab, along with their severity level, which would be mitigated because of the upgrade.
. Click *Generate Upgrade Plan* to navigate to *Upgrade Advisor*.
