---
sidebar: sidebar
permalink: task_generate_reports.html
keywords: reports, generate reports
summary: Provides information to generate reports.
---

= Generate reports
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can generate reports immediately or schedule a report to be generated on a weekly or monthly basis. You can generate reports for areas like inventory, wellness, and configuration (ClusterViewer).

*About this task*

* You cannot edit the reports in Active IQ. You should delete the existing report and create a new report.

.Steps
. From the left pane, click *Reports*.
. Click *Create Report* to generate a new report.
+
You can generate a report immediately or you can schedule the report to be generated on a weekly or monthly basis.

[cols=2*,options="header", cols="50,50"]
|===
| To generate a report immediately
| To schedule the report to be generated on a weekly or monthly basis
a|
. Select the type of report and provide the requested values for the report.
. Click *Submit*.

NOTE: The report is saved in Active IQ for 3 days.

a|
. Click the *Schedule Report* tab.
. Select the type of report and provide the requested values for the report.
. Select the frequency of the report.
. Select the start date and end date for the report.
. Click *Submit*.

NOTE: The next scheduled report will replace the existing report.

|===
