---
sidebar: sidebar
permalink: task_view_risk_and_take_action.html
keywords: wellness, performance, efficiency, availability, capacity, security vulnerabilities, protection, protect, mitigate, rectify
summary: Provides information to view and analyze the wellness of your storage system and mitigate the risks.
---

= View storage system risks in Digital Advisor and take corrective actions
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can analyze the wellness attributes of your storage system by viewing the actions and risks associated with them. You should view the associated corrective actions and manually mitigate the risk.

.Steps
. Click the *Wellness*  widget on the dashboard or click *View All Actions* to view the list of all the actions and risks.
. View the *Actions* and *Risks* associated with the wellness attribute.
. Click *Actions* to view the risks associated with the actions, click *Risks* to view all the risks, or click *Affected Systems* to view the systems that require attention.
. Click the risk name to view information about the risk.
. Click the associated corrective actions and follow the information to resolve the risk.

The steps to mitigate the risks are same for all wellness attributes. You can view the following video to monitor and fix security related issues:

video::ssXI-FAKMis[youtube, width=848, height=480]
