---
sidebar: sidebar
permalink: task-integrating-with-cloud-insights-to-view-vm-details.html
keywords: Cloud Insights, VMs, virtual machines
summary: Provides information about the virtual machines in Cloud Insights
---

= Integrating with Cloud Insights to view Virtual Machines details
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Active IQ is now integrated with Cloud Insights Basic version to provide a full stack inventory and interoperability checks to customers.

The benefits of this integration are:

* Simplified SaaS monitoring of ONTAP
* Visibility into VMware full-stack monitoring
* Productivity savings for customers through automated interoperability checks to help with ONTAP upgrade planning. This results in smoother ONTAP upgrades and reduces risks of incompatibility with hosts.

NOTE: This feature is available only for SupportEdge Advisor, SupportEdge Expert, and Active IQ Upgrade contracts.

.Steps
. In the *Inventory* widget, click *Virtual Machines* to view the data available in Cloud Insights.
. Click the *Virtual Machine Overview* tab.
. Click the *Count of ESX Hosts* to view information about the host.
. Click the *ESX Name* to navigate to Cloud Insights to view more information.
