---
sidebar: sidebar
permalink: task_execute_ansible_playbook_without_docker.html
keywords: ansible playbook, ansible, playbook, without docker
summary: Provides information to execute ansible playbook using the docker image.
---

= Execute Ansible playbook without NetApp Docker image
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

.Steps
. Install link:https://docs.python.org/3/using/windows.html[Python] and link:https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible].
. Install the required Python packages by using *pip*:
+
----
$ pip install netapp-lib requests
 
Installing collected packages: netapp-lib, requests
Successfully installed netapp-lib-2020.3.12 requests-2.23.0 
----
. Install NetApp Ansible collection by using the *ansible-galaxy* command:
+
----
To install the collection only for the current user
$ ansible-galaxy collection install netapp.ontap
 
To do a more universal installation,
$ ansible-galaxy collection install netapp.ontap -p /usr/share/ansible/collections

$ chmod -R +rw /usr/share/ansible/collections
----
For more information about the ansible-galaxy command, refer to link:https://docs.ansible.com/ansible/latest/cli/ansible-galaxy.html[Ansible Galaxy Documentation] and for more details about the NetApp Ansible Collection, refer to the link:https://galaxy.ansible.com/netapp/ontap[NetApp Ansible Collection page].

. Execute the Ansible playbook by using *ansible-playbook* command:
+
----
$ cd <downloaded_playbook_path>
$ ansible-playbook na_ontap_pb_upgrade_firmware.yml
 
Enter your ONTAP admin username: ****
Enter the password for your ONTAP admin user: ****
Enter the base URL to the firmware package (using HTTP is recommended): http://<web-server>/path/
PLAY [ONTAP Firmware Upgrade] ****************************************************************
----

For more information about the *ansible-playbook* command, refer to the link:https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html[Ansible Playbook Documentation] and to execute the Ansible playbook in check mode (dry run), refer to link:https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html[Ansible: Check mode].

After executing the playbook, refer to the link:task_validate_firmware_installation.html[Firmware Installation Validations] for post execution instructions.
