---
sidebar: sidebar
permalink: task_view_API_catalog.html
keywords: API Catalog, APIs, integrate data, view catalog
summary: Provides information about the APIs available in the API Catalog.
---

= Use API Catalog to execute APIs
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The API Catalog allows you to browse through categories and the available APIs within each of those categories.

Using a valid Access Token and correct inputs for the required fields, you can make a test call for an API.

== Access GraphQL APIs
.Steps
. From the *Quick Links* menu, click *API Services*.
. Click link:https://activeiq.netapp.com/catalog/internal/api-reference/introduction[Browse] under the *API Catalog* icon.
+
The API Catalog is displayed.
. Click *GraphQL* and review the documentation. 
. Try out the GraphQL APIs by using the ready-to-run sample queries at link:https://studio.apollographql.com/public/ActiveIQ-Graph-Prd-API/variant/current/explorer?collectionId=251c50ce-797e-4549-bb9c-f6557ef5a176OPERATION_COLLECTIONfocusCollectionId=251c50ce-797e-4549-bb9c-f6557ef5a176[Digital Advisor GraphQL Studio^]. 
. Supply a user token by selecting the authorization field in the Header of the API request 
. Provide the required variables
. Run the query and review the output



== Access REST APIs
.Steps
. From the *Quick Links* menu, click *API Services*.
. Click link:https://activeiq.netapp.com/catalog/internal/api-reference/introduction[Browse] under the *API Catalog* icon.
+
The API Catalog is displayed.
. Click *ActiveIQ-Public* and select any API
. At the top of the page, slide the toggle to “Experiment”.
. From the left navigation, expand the categories and select any API to view detailed information.
. Expand the API.
. Click the *Try it out* button on the right.
. Provide the required parameters and click *Execute* to view the results.
+
You can also examine the *Responses* section of the API to understand the data that will be returned better. You can click on *Example Value* to see the format of the data or click on *Model* and click on the carets to expand the sections to see the definition of each element.

By sliding the toggle to the *Code* view, you can view code samples in various languages.
