---
sidebar: sidebar
permalink: task_compare_config_drift_template.html
keywords: config deviation, drift, configuration, compare template
summary: Provides information to compare a configuration drift template.
---

= Compare config drift templates in Digital Advisor
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can compare the system and cluster configurations and detect the configuration deviations in near real time.

.Steps
. From the left pane, click *Config Drift*.
. Select one of the existing templates or click *Add Template* to add a new template.
. Generate a config drift report
+
You can generate a report immediately or you can schedule the report to be generated on a weekly or monthly basis.

[cols=2*,options="header", cols="50,50"]
|===
| To generate a report immediately
| To schedule the report to be generated on a weekly or monthly basis
a|
. Select a category and provide the requested values for the report.
. Select *Include only drifts* option to download only the configuration deviation changes.
. Click *Submit*.
. link:task_generate_reports.html[Download and view the config drift report].
. Run Ansible Playbook (included as part of the config drift report) to mitigate the drifts.
a|
. Click the *Schedule Report* tab.
. Select a category and provide the requested values for the report.
. Select *Include only drifts* option to download only the configuration deviation changes.
. Select the frequency of the report.
. Select the start date and end date for the report.
. Click *Submit*.
. link:task_generate_reports.html[Download and view the config drift report].
. Run Ansible Playbook (included as part of the config drift report) to mitigate the drifts.
|===
An email is sent with the details of the configuration deviation between the selected systems.
