---
sidebar: sidebar
permalink: task_subscribe_to_wellness_review_email.html
keywords: wellness, wellness review subscription, 1 month, delete, unsubscribe, subscriptions, supportedg expert, supportedge advisor, monthly, email, activeiq, active iq digital advisor
summary:
---

= Subscribe to wellness review email
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can subscribe to the wellness review email to receive a monthly email that summarizes wellness status, systems that are nearing its renewal dates, and systems that require an upgrade for the NetApp products in your installed base.
You will receive a wellness review email so that you can view a monthly summary and take action for your systems.
At any time, if you decide to not receive email, you can unsubscribe from getting email. You can also delete subscriptions.

After the subscription is enabled, you should select a start date when adding subscription.
The monthly email summary provides a view of outstanding wellness, renewal, and health check actions. You can confirm the email address and the email is sent to the specified email address.

NOTE: This feature is available only through NetApp SupportEdge Advisor and SupportEdge Expert service offerings.

.Steps
. On the Dashboard, click *Wellness Review Subscription*.
. Click *Wellness Review Subscription*.
. Click *Add Subscription*.
. Provide the required information in the *Name the Subscription*, *Choose Category*, *Search Customer*, and *Email* fields in the *Add New Subscription* dialog box.
. Click *Subscribe*.
Upon successful subscription, you will receive a *Subscription was added* message.
