---
sidebar: sidebar
permalink: task_execute_ansible_playbook_without_docker.html
keywords: Ansible Playbook, Ansible, playbook, without docker
summary: Provides information on how to execute Ansible Playbook using the docker image.
---

= Run the Ansible playbook without the NetApp Docker image
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

.Steps
. Install link:https://docs.python.org/3/using/windows.html[Python^] and link:https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible^].
. Install the required Python packages using *pip*:
+
----
$ pip install netapp-lib requests paramiko
 
Installing collected packages: netapp-lib, requests, paramiko
Successfully installed netapp-lib-2020.3.12 requests-2.23.0  paramiko-2.7.2
----
. Install NetApp Ansible collection using the *ansible-galaxy* command:
+
----
To install the collection only for the current user
$ ansible-galaxy collection install netapp.ontap
 
To do a more universal installation,
$ ansible-galaxy collection install netapp.ontap -p /usr/share/ansible/collections

$ chmod -R +rw /usr/share/ansible/collections
----
For more information about the ansible-galaxy command, refer to link:https://docs.ansible.com/ansible/latest/cli/ansible-galaxy.html[Ansible Galaxy Documentation^] and for more information about the NetApp Ansible Collection, refer to the link:https://galaxy.ansible.com/netapp/ontap[NetApp Ansible Collection page^].

. Execute the Ansible Playbook using *ansible-playbook* command:
+
----
$ cd <downloaded_playbook_path>
$ ansible-playbook na_ontap_pb_upgrade_firmware.yml
 
Enter your ONTAP admin username: ****
Enter the password for your ONTAP admin user: ****
Enter the base URL to the firmware package (using HTTP is recommended): http://<web-server>/path/
PLAY [ONTAP Firmware Upgrade] ****************************************************************
----
NOTE: If there are a set of clusters with different login credentials, the Ansible Playbook must be run on each cluster. There are no changes required to the inventory file as the Ansible Playbook skips the clusters for which the login has failed.

For more information about the *ansible-playbook* command, refer to the link:https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html[Ansible Playbook Documentation^] and to execute the Ansible Playbook in check mode (dry run), refer to link:https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html[Ansible: Check mode^].

After executing the playbook, refer to the link:task_validate_firmware_installation.html[Firmware Installation Validations] for post-execution instructions.
