---
sidebar: sidebar
permalink: task_add_watchlist.html
keywords: dashboard, watchlist, add watchlist
summary: Provides information to add a watchlist to the dashboard.
---

= Add a watchlist to the Dashboard
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Create a watchlist to access preselected systems inside Active IQ quickly and easily. You should create a new dashboard to add a watchlist.

The maximum number of dashboards that you can create is 25.

.Step
. Click *+ Add New Dashboard*.
+
You can import an existing watchlist or create a watchlist.
. Provide a name for the watchlist.
. Select *Category* or *Serial Number*, and follow the steps listed to add systems to the watchlist.
+
You can add a maximum of 15,000 systems under category and 500 systems under serial number.
. Click *Next*.
. Provide a name for the dashboard.
. Select the widgets to be added to the dashboard.
. Optionally, you can make this dashboard as your default dashboard.
. Click *Create* to add the watchlist to the dashboard.
