---
sidebar: sidebar
permalink: task_view_performance_graphs.html
keywords: performance, performance graph, graphs, activeiq, active iq digital advisor, performance charts, day, week, 1 month, 2 months, calendar, chart data, performance on node level, graph, node level
summary: Provides information about the performance.
---

= Analyze performance graphs
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Performance graphs enable you to analyze the performance of your storage devices. You can view detailed performance graphs for an ONTAP cluster or multiple nodes of an ONTAP cluster and E-Series controllers. These graphs provide historical performance data, which can be used for understanding performance trend and pattern analysis. You can select a date from the calendar to view performance graphs for a day, week, month, two months, and twelve months. You can select multiple nodes to view a particular graph at the same time.

You have an option to set preferences, for example, you can view either one graph for three nodes or two graphs for three nodes.

When the graph is first displayed, a 1-week tab is preselected and it presents data for a 1 week in a graphical format to make it easier to understand large quantities of data and its relationship between different series of data. If you want to reset the date range, for example, you can click 1-month tab and select dates in the calendar.

You also have an option to zoom in performance graph; the individual data points are displayed.

video::fWrHYX17xT8[youtube, width=848, height=480]

.Steps
. On the Dashboard, click *Performance*.
+
For ONTAP systems, you can click the *Node* tab to view the performance of a single node of an ONTAP cluster, click the *Local Tier* tab to view the performance of the local tier, or click the *Volume* tab to view the performance of the volume. By default, the cluster performance is displayed.
+
For E-Series systems, you can view the graphs only at a controller level.

[start=2]
. Select either 1 day, 1 week, 1 month, 2 months, or 12 months, in the calendar, for viewing performance data in a graphical format.
+
For example, select 2-months tab to view data for 2 months. This enables you to view specific data for a duration based on your performance requirements.
. The following performance graphs with required metrics are available for ONTAP clusters and nodes:

[cols=4*,options="header",cols="25,25,25,25"]
|===
| For Cluster
| For Node
| For Local Tier
| For Volume
| IOPS | CPU Utilization - Peak Performance (Headroom) | Average Throughput| IOPS
| Network Throughput | Latency  | Average Utilization | Latency
|   | IOPS |   |
|   | Protocol IOPS |  |
|   | Network Throughput |  |
|===

NOTE: Node latency performance graphs and volume performance graphs are supported only on systems that are running ONTAP 9.2 and later.

[start=4]
. The following performance graphs with required metrics are available for E-Series controllers:
** CPU Utilization
** Latency
** IOPS
** Throughput
