---
sidebar: sidebar
permalink: task_identify_capacity_system.html
keywords: capacity, space, increase,
summary: Provides information to increase the capacity of the system.
---

= Identify systems reaching capacity limits
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Proactively identify systems reaching capacity limits and send a request through live chat to increase the capacity of your storage system.

You can view systems that have exceeded 90% capacity or are to exceed 90% capacity in 1, 3, and 6 months. Chat with a salesperson to raise capacity addition requests easily and get real-time assistance.

.Steps
. In the *Planning* widget, click *Capacity Additions* to view the systems that have exceeded 90% capacity or are nearing 90% capacity.
+
You can view the number of systems that have exceeded 90% capacity or are to exceed 90% capacity in the next 1, 3, and 6 months.
. Select a card to view the systems.
. Select the systems for which you want to increase capacity  and click *Contact Sales*.
. Verify your contact details.
. Copy and paste up to five hostnames into the chat to raise capacity addition requests.
