---
sidebar: sidebar
permalink: task_protect_systems_against_ransomware_risks.html
keywords: ransomware, risks, ransomware risks
summary:
---

= Protect storage systems managed by Digital Advisor from ransomware risks
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

When you log in to the Digital Advisor, you can view the *Actions* highlighted on the *Security & Ransomware Defense* widget, which shows the risk counts.

You can view the snapshot creation, retention, and ONTAP FPolicy risks, and then take actions to fix them.

.Steps
. Log in to Digital Advisor.
. Select *Actions* on the *Security & Ransomware Defense* widget.
. Clear the *Security Vulnerabilities* checkbox.
. For the risks that are displayed, check the impact level and follow the recommended actions.
. Select the Unique Risks tab and link in the *Corrective Action* column.
. Select the *Affected Systems* tab to view systems with risks.
. Follow remediation actions that are recommended to protect the systems.

// 29-JULY-2026 updated snapshot capitalization to meet current standards
