---
sidebar: sidebar
permalink: upgrade_advisor_overview.html
keywords: Upgrade Advisor, upgrade plan, ONTAP, upgrade recommendation, clusters, storage systems
summary: Provide an overview of Upgrade Advisor that simplifies the planning for an ONTAP upgrade.
---

= Overview
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Upgrade Advisor enables you to generate an upgrade plan that includes detailed and step-by-step information required for a successful ONTAP upgrade or revert. 

You can generate automated nondisruptive upgrade plans for a single cluster and multiple clusters. You can view upgrade recommendations only for a single cluster, which includes a list of risks associated with a cluster, a pre-upgrade check report containing a list of upgrade blockers and warnings, and information about new features and enhancements. To learn more, see link:generate_upgrade_plan_single_multiple_clusters.html[Generate an upgrade plan for single cluster and multiple clusters].

[NOTE]
====
* For each cluster in a MetroCluster configuration, generate an individual upgrade plan for complete upgrade instructions.
* ##For clusters running ONTAP 9.7 or older versions, you can view the information about new features and enhancements in upgrade recommendations.The pre-upgrade check report and risk summary are unavailable, and you can generate an upgrade plan in the older format.##
====

Before generating an upgrade plan, you should prepare for an ONTAP upgrade. Proper preparation helps in identifying and mitigating potential upgrade risks or blockers before you begin the upgrade process. To learn more, see link:https://docs.netapp.com/us-en/ontap/upgrade/prepare.html[Prepare for an ONTAP upgrade^].
