---
sidebar: sidebar
permalink: view_keystone_capacity_utilization.html
keywords: keystone, capacity utilization, service tiers, Keystone subscription, keystone subscription, shares, disks
summary: Provides information on your capacity utilization with NetApp Keystone Subscription.
---

= View capacity utilization with NetApp Keystone Subscription
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you are subscribed to NetApp Keystone STaaS services, you can view the Keystone Subscription widget on the Digital Advisor Dashboard.

The Keystone Subscription widget provides you a summary of the capacity usage for your account. It consists of capacity utilization charts with respect to the physical capacity, the snapshot being rounded up to the last five minutes. The utilization over and above the committed capacity (the burst capacity) is marked in red.

NOTE: As an Digital Advisor user, you can choose between ONTAP Collector and AutoSupport to obtain data on your capacity usage.

For more information about the various levels of subscription data and usage information, see link:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-aiq.htmll[Keystone and Digital Advisor^].
    