---
sidebar: sidebar
permalink: concept_aiq_value_report.html
keywords: Active IQ, value report
summary: Provides an overview of the value report feature.
---

= Value Report
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/UserGuide

The value report is a summary of benefits you received through Active IQ and your support contract. For selected systems, the value report consolidates the following benefits from last one year.

[cols=",",options="header",cols="20,80"]
|========================================================================================================================================
|Components of value report |What does value report show and why should you care?
|Support cases opened and resolved |This component summarizes all support cases that were resolved during the last year, for selected systems. Resolution of support cases is one of the biggest benefits you receive from your support contract. NetApp invests significantly in enhancing its product telemetry and support automation capabilities. As a result, you see improvements in resolution time for cases as NetApp narrows down issues faster and ensures support cases are handled most efficiently by NetApp Support personnel.

|Software upgrades |This number reflects the ONTAP upgrades you have performed for selected systems over the last one year.

Software upgrades help improve system reliability and in turn better serves your business applications. Additionally, software upgrades also allow you take advantage of newer features and functionalities.

If you have a valid support contract, you continue to receive newer and better software for your systems.
|Unique applications detected |This value shows applications detected for selected systems using signatures, heuristics, and other advanced algorithms applied by NetApp to your system telemetry.

This information is valuable for determining which applications are being served by systems included in the value report and helps you make more informed decisions while you are deciding whether to renew support contracts.

If NetApp systems are serving your business applications, you should always consider renewing support contract to ensure you receive ongoing and timely support for your systems.
|Storage efficiency savings |For ONTAP 9.1 and above systems, this component reflects the savings you have received by taking advantage of various NetApp storage efficiency features including deduplication, compression, Snapshot copies, clones, and compaction.

When you renew the support contract, you will be able to leverage newer ONTAP versions to get more savings from improvement to existing efficiency features as well as new efficiency features that NetApp may introduce.
|Days till earliest contract |This value shows you the number of days left until you have a system in need of a support contract renewal. Knowing when a support contract expires allows you to prepare better for its renewal.

If you have few days till the earliest contract renewal, you should contact Support Contract Renewal team through the support renewal capability in your Active IQ dashboard or reach out to your contact for NetApp systems.
|Proactive System Risks |In this section of the value report, you will see a summary of the following for selected systems:

* Total risks signatures checked
* System risks mitigated – each of these mitigated risks equate to a problem that you avoided.

Proactive risk notifications fall in following categories:

* Configuration
* Security
* Performance and Efficiency
* Capacity
* Availability and protection

NetApp makes significant ongoing investments to proactively detect risks in your environment. After detecting these risks, we classify risks by impact and notify you how to mitigate these risks. To further help with mitigation, Active IQ will show whether the mitigation is non-disruptive (for example, a simple configuration change) or disruptive (for example, a major upgrade) so that you can better plan your mitigation.


|========================================================================================================================================
