---
sidebar: sidebar
permalink: concept_ug_customer_my_systems.html
keywords: Active IQ, user guide, cluster dashboard, my systems
summary: Provides an overview of the my systems feature available in customer dashboard.
---

= My Systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/UserGuide

=== Aggregated View of Multiple Customers (Partners Only)

Available from the *My Systems* link on the top banner of the application, this aggregated view provides partners (only) with a way to see all of their customers’ information from a single screen. The view displays a list of partners’ customers, provides a count of the systems for each customer, and shows which sites these customers have.

In addition to these details, this view also shows the number of risks and end-of-support components for each customer and site, as well as AutoSupport adoption for each customer.

This view also offers a detailed worksheet that you can download for each customer. The downloaded report includes the following fields:

[cols=",",]
|=======================
a|
* Cluster Name
* Hostname
* Serial #
* System ID
* Customer
* Site
* Group
* Entitled Access Status
* Last AutoSupport Date

a|
* # of Risks
* # of EOS HW
* Model
* Data ONTAP Version
* Ship Date
* Contract End Date
* Contact Information
* Name, E-Mail, Phone
