== Upgrade Advisor
A multi-format download option has been included for Upgrade Advisor plans to simplify ONTAP upgrade planning and address potential blockers or warnings. You can now download upgrade advisor plans in Excel, PDF, and JSON formats. 

=== Enhancements in Excel format
* You can view the pre-checks performed on the cluster, flagging the results with indicators such as “Passed,” “Failed,” or “Skipped.” This ensures that the cluster is in optimal condition for completing the ONTAP upgrade.
* You can view the recommended latest firmware updates applicable to the cluster, along with the version shipped with the ONTAP target version. 
* A new tab has been included that offers interoperability checks for SAN clusters. It provides a view of the supported Host OS versions for the selected target ONTAP version. 

=== Enhancement in JSON format
You can view the pre-checks performed on the cluster, offering warnings and blockers to review before initiating seamless upgrades. This helps to identify issues requiring attention before upgrading multiple systems and enables direct integration of the JSON output into the automation processes.
