---
sidebar: sidebar
permalink: task_view_upgrade.html
keywords: upgrade, current version, benefits
summary: Provides information to view and upgrade your storage system.
---

= View and upgrade your storage system
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
View the pending upgrades of your storage system and the current interoperability data. The interoperability data is populated based on the Active IQ OneCollect AutoSupport data.

.Step
. In the *Upgrade* widget of the dashboard, click *Upgrades* to view the pending upgrades.
. In the *Upgrade* widget of the dashboard, click *Current Interoperability* to view the supported, unsupported, and remediation information.
. Click the pending upgrades or click *View All* to view all the pending upgrades.
+
You can view the number issues that will get fixed on upgrade.
. Select the required upgrade option.
. View the documentation and future interoperability.
. Compare the different options for upgrade before planning the upgrade.
. View the risks in the targeted version
. Click *Plan Upgrade*.
. Add systems or select systems to view peer compatibility and click *Next*.
. Click *Next*.
. Select the required values and click *Generate*.
